### ISSUE TITLE
Add Support for ESP32 C3

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1071]
### Description

Add support for the C3 series.

**Comment by KiwiBryn** [comment]
Got one of these sitting on my desk ready to go for testing...
https://www.seeedstudio.com/Seeed-XIAO-ESP32C3-p-5431.html
![image](https://user-images.githubusercontent.com/12842169/194737076-a582abbc-0d7c-4001-9ffe-b714d7f1da45.png)

**Comment by lanmark7** [comment]
Hoping to use nanoframework with the C3 series..  the seeed board is a really nice configuration of wifi/bluetooth as well as it has a charge controller for adding a rechargeable battery.   Has there been any movement on adding C3 support?

**Comment by torbacz** [comment]
@josesimoes Haven't you done it?

**Comment by josesimoes** [comment]
@torbacz yes! Just forgot to link to this issue here... 🤦🏻‍♂️

**Comment by josesimoes** [comment]
Implemented with nanoframework/nf-interpreter#2471.

**Comment by goblinmaks** [comment]
ESP32-C3 rev.0.4 not supported 

![image](https://github.com/nanoframework/Home/assets/1436234/699890e8-f89b-43da-8514-6d158e0b9c5e)
@josesimoes is possible to add support ?
