### ISSUE TITLE
System.IO.Streams causing warning

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#1096]
### Details about Problem
`IoT.Devices` is using the latest version, but many other libraries are behind.

![image](https://user-images.githubusercontent.com/11439699/179297933-4d4029d1-ad29-4ff9-b4ff-70d42ac42adf.png)

We should "bump" the version so that they are in sync.

**nanoFramework area:** ( Visual Studio extension | Other tools )

**VS version:**

**VS extension version:**

**Target:**

**Firmware image version:**

**Comment by josesimoes** [comment]
Should be fixed with https://github.com/nanoframework/System.IO.Streams/commit/1d93ec799f0ba6e43b20314824d127e17ad15806
