### ISSUE TITLE
Add packages lock to all libraries

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1162]
### Details about Problem

Need to add packages lock file to all class library repos.

### Description

Use this PR as guideline: nanoframework/nanoFramework.Networking.Sntp#118.

To create the packages.lock.json file: 

1. Open a command prompt in the repo root
2. Delete the packages folder
3. enter `nuget restore -uselockfile`

**Comment by Ellerbach** [comment]
Maybe you can as well give the steps on how to generate/create the packages lock file?

**Comment by networkfusion** [comment]
> Maybe you can as well give the steps on how to generate/create the packages lock file?

As simple as building the project in visual studio after adding an empty file.

**Comment by networkfusion** [comment]
Adding this for reference... https://github.com/search?q=org%3Ananoframework+project.lock&type=code
Also including the warning about `gitignore` excluding `project.lock.json` in some repos!

**Comment by josesimoes** [comment]
This should be pretty much completed. Any library that's missing it will be updated later.
