### ISSUE TITLE
Update github actions on all repos

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1163]
### Details about Problem

Update/add github actions to most of the repos.

### Description

Use this as inspiration: https://github.com/nanoframework/nanoFramework.Networking.Sntp/tree/main/.github/workflows

**Comment by weslleymurdock** [comment]
Hello, I'm interested to help on this one. How i may help here?

**Comment by networkfusion** [comment]
Hey @weslleymurdock , this is interlinked with  #1162 , please check there and choose a repo that needs work (basically any of the managed libs that have not been updated in the last couple of weeks), and make the suggested changes.

**Comment by weslleymurdock** [comment]
Thanks a lot. I will take a look on the mentioned issue and start

**Comment by networkfusion** [comment]
@josesimoes I think we are probably done here?!

**Comment by josesimoes** [comment]
I would agree.
