### ISSUE TITLE
Helper Method to Re-Format Internal Flash Drives on Boards that Support It

### ISSUE THREAD

**Issue by gligorov** [nanoframework/Home#1229]
### Description

At present there is no way to reformat the internal flash on devices.  If for any reason, format is needed, ( security, troubleshooting etc.), there is no way to do that.

### How to solve the problem

Add a simple helper method like  Format(string driveLetter) or something similar to be used from a library that is best suited for this.

### Describe alternatives you've considered

none at present

**Comment by josesimoes** [comment]
Nope. This requires a native call in order to restart/format the file system or SPIFFs. When it comes to this, it's because the file system got unusable.

**Comment by torbacz** [comment]
Maybe command with nanoff will be sufficient?

**Comment by networkfusion** [comment]
@josesimoes should this be closed now?

**Comment by josesimoes** [comment]
> @josesimoes should this be closed now?

The linked PR has added support for this only for SPIFFs storage. I think it should be extended to the other supported storage: SD Cards and USB MSD. That's why I left it open.
