### ISSUE TITLE
Missing dotnetfoundation img 

### ISSUE THREAD

**Issue by Arhell** [nanoframework/Home#1265]
### Description

Missing dotnetfoundation img  on this page https://github.com/sponsors/nanoframework

### How to solve the problem

![Screenshot_1](https://user-images.githubusercontent.com/26163841/229931025-cb14817a-5959-408e-bf3e-942f64ea0859.png)
link to img https://raw.githubusercontent.com/dotnet-foundation/website/main/input/img/logo_big.svg

**Comment by josesimoes** [comment]
Fixed! Thanks for reporting.
