### ISSUE TITLE
Error in `ToString()` from float

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1282]
### Discussed in https://github.com/nanoframework/Home/discussions/1281

<div type='discussions-op-text'>

Output of `ToString()` from float args is wrong.

```csharp 
float x = 0.01f * 0.01f;
Console.WriteLine($"Result: {x}  DataType: {x.GetType()}");
```

output is:

`Result: 0 DataType: System.Single`

**Comment by sky9mike** [comment]
We see this too. Can inspect value in debugger but string formatting is broken for float and double. I created a sample at https://github.com/Skyworks-Timing-Software/publicNanoframeworkSamples/tree/main/nanoFrameworkFloatFormattingIssue
```
// On .NET4.8 the following yields:
//
// 1.2345E-09
// 1.2345E-09
// 1.23450E-009
// 1.23450E-009
//
// On nF yields:
//
// 0
// 0
// E5
// E5

double value = 1.2345e-9;

Debug.WriteLine(value.ToString());
Debug.WriteLine($"{value}");
Debug.WriteLine(value.ToString("E5"));
Debug.WriteLine($"{value:E5}");

```
