### ISSUE TITLE
ESP32 C3 unable to create PWM channel with 50Hz frequency

### ISSUE THREAD

**Issue by torbacz** [nanoframework/Home#1298]
### Target name(s)

ESP32_C3_REV3

### Firmware version

1.8.1.233

### Description

When trying to use servo it's required to use 50Hz PWM channel, yet it fails to create.
![image](https://github.com/nanoframework/Home/assets/19893965/b89e4f26-deae-4d7b-9c98-a71916e10562)

The same code with 5000 frequency works fine, so the pin supports PWM.
![image](https://github.com/nanoframework/Home/assets/19893965/ec67c220-a053-4d66-9c8f-fbb8829aca00)

### How to reproduce

```
  const short servoPin = 13;
  nanoFramework.Hardware.Esp32.Configuration.SetPinFunction(servoPin, nanoFramework.Hardware.Esp32.DeviceFunction.PWM1);
  // Set up PWM
  var pwm = PwmChannel.CreateFromPin(servoPin, 50);
```

**Comment by Ellerbach** [comment]
@torbacz you mention in the Discord channel that a speed of 50000 works, correct?

**Comment by Ellerbach** [comment]
The issue is then somewhere here: https://github.com/nanoframework/nf-interpreter/blob/20c26decce053f1c1b50e1a599928e1b4d1d10b3/targets/ESP32/ESP32_C3/nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp#L187-L188

PWM implementation for C3 is specific. So most likely something not exactly correct.

**Comment by Ellerbach** [comment]
A quick look at the IDF docs shows that for low frequency, some specific settings may need to be applied, that's probably the reason of the issue. See https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32c3/api-reference/peripherals/ledc.html. It seems to fails when trying to find the divider. So more investigations needed.

and indeed, if you have a normal ESP32, you should use it in the meantime.

**Comment by matsujirushi** [comment]
Hi @Ellerbach ,

> https://github.com/nanoframework/nf-interpreter/blob/20c26decce053f1c1b50e1a599928e1b4d1d10b3/targets/ESP32/ESP32_C3/nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp#L187-L188

It looks like the build system doesn't use this file.

**build.ninja:**

```
...
build targets/ESP32/ESP32_C3/CMakeFiles/NF_NativeAssemblies.dir/__/_nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp.obj: CXX_COMPILER__NF_NativeAssemblies_Debug /workspaces/nf-interpreter/targets/ESP32/_nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp || cmake_object_order_depends_target_NF_NativeAssemblies
...
```

`/workspaces/nf-interpreter/targets/ESP32/_nanoCLR/System.Device.Pwm/sys_dev_pwm_native_System_Device_Pwm_PwmChannel.cpp`

Is this behavior correct?

**Comment by matsujirushi** [comment]
I will try to solve this issue.
Please assign me.
