### ISSUE TITLE
Fix Unit Tests in Azure.Devices library

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1304]
### Details about Problem

**nanoFramework area:** nanoFramework.Azure.Devices

### Description

Following the recent update on the test framework Unit Tests are failing in nanoFramework.Azure.Devices library:
https://dev.azure.com/nanoframework/Azure.Devices/_build/results?buildId=42349&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7bfb7e0f-549d-5929-c603-6e8046613b9e

Need to clone the PR there run locally and fix them.
https://github.com/nanoframework/nanoFramework.Azure.Devices/pull/291

Note: this is high priority because its breaking the build.

**Comment by torbacz** [comment]
@josesimoes Fixed already?

**Comment by josesimoes** [comment]
Yes. Unit tess all a green again! 👍

**Comment by josesimoes** [comment]
Nope. Still open.

**Comment by torbacz** [comment]
But new pipelines are working, with latest version of test framework
![image](https://github.com/nanoframework/Home/assets/19893965/4701e9b1-a148-4957-be7b-61ada9a173e9)

**Comment by josesimoes** [comment]
Yes, that got fixed too. I was under the impression that it wasn't... apologies

**Comment by josesimoes** [comment]
Closed by nanoframework/nanoFramework.Azure.Devices#292
