### ISSUE TITLE
API docs aren't linking to the source code file

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1324]
### Details about Problem

**nanoFramework area:** ( docs )

### Description

Standard docfx generated pages show a link to "Improve this document" and for APIs the methods link to the source code file in the respective github repo.
Like this:

![image](https://github.com/nanoframework/Home/assets/1881520/dd258127-8571-488b-a97b-d4e4b1bb401a)

This used to be there. As it is today it's not. Something in the docfx config or the parsing that occurs in the pipeline must be preventing this from being added to the docs.

This is a very convinient feature and we should have it back.

**Comment by josesimoes** [comment]
@Ellerbach maybe you have some thoughts about this... 😉

**Comment by Ellerbach** [comment]
> @Ellerbach maybe you have some thoughts about this... 😉

Yes, indeed, the "origin" repo is used as the source, so nanoframework.github.io. Because we clone all the rest, assemble elements from everywhere, the source is not adjusted. I haven't checked in details if there is a way to adjust this. Most probably, we would have to deactivate this feature.

**Comment by josesimoes** [comment]
This used to be there. I recall having used it in the past to navigate to the source code file in the repo. I'm guessing something is missing for docfx to be able to link to it.
