### ISSUE TITLE
VS extension fails to load following update to VS2022 v17.12

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1550]
### Tool

Visual Studio extension

### Description

On loading VS, there is a message about the extension failing to load.
The "detail" on VS activity log is useless:
` [Visual Studio 2022 extension for .NET nanoFramework. Enables creating C# Solutions to be deployed to a target board and provides debugging tools.](null)`
 

### Aditional context

Started following update to VS2022 to v17.12.

Reported to Dev Community [here](https://developercommunity.visualstudio.com/t/SetSite-failed-for-package/10789060).

## ⚠️  PLEASE UPVOTE there and add your feedback to raise the issue priority

**Comment by 28106830** [comment]
Close plugin
Just enable the plugin again

**Comment by 28106830** [comment]
Temporary handling methods
1. First in VS2022
2. Close the Device Explorer window
3. Close VS2022
4. Just open it again
