### ISSUE TITLE
Failling to update nanoCLR in test framework

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1564]
### Tool

Visual Studio extension

### Description

Failing to update nanoclr in test run doesn't output the error message.
Reported in Discord [here](https://discord.com/channels/478725473862549535/1315343474845028504/1315343477952741518)

### Aditional context

Should check why the verbose output is not happening properly.

cc @Ellerbach

**Comment by Ellerbach** [comment]
I still have the issue after cleaning my repo, updating the test framework, ran the test
