### ISSUE TITLE
SWO output does not work on Nucleo-F746ZG

### ISSUE THREAD

**Issue by MikroBusNet** [nanoframework/Home#212]
No matter which frequency I use, the same code that is working on the F429iDisco does not display anything with the F746.

**Comment by josesimoes** [comment]
It was missing a setPadMode to the PB3 pin because it's being set to another mode on board init.
(this got lost from the original PR for SWO...)
Also make sure that you set the correct Sys clock in the SWO viewer. It's 216MHz for the Nucleo-F746ZG.
