### ISSUE TITLE
Add reference targets to nF overlay folder

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#217]
(just the ones that require tweaking, one on each PR please)

**Comment by josesimoes** [comment]
Actually this is only required for boards that do NOT exist at all.
If it's a matter of tweaking board.c and board.h this is already covered in CMake.
In this case those files can be simply added to the target folder along with the rest.

**Comment by MikroBusNet** [comment]
Then we change nothing. Closing this issue.
