### ISSUE TITLE
Update the CMakeList.txt in the community targets

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#231]
To take advantage of the improvements brought in ~nanoFramework/nf-interpreter#512 and  nanoFramework/nf-interpreter#513~ ~nanoFramework/nf-interpreter#517~ nanoFramework/nf-interpreter#522.

**Comment by networkfusion** [comment]
@piwi1263 have you not done this?

**Comment by josesimoes** [comment]
Yes, for sure! All community targets are building correctly so this is definitely implemented.
