### ISSUE TITLE
Add separate compiler flags for C and C++

### ISSUE THREAD

**Issue by MikroBusNet** [nanoframework/Home#236]
Some gcc flags apply only to C or to C++. This generates one warning per flag et per file for the misused flag.

**Comment by josesimoes** [comment]
This can prove a bit tricky...
We just left the CMAKE_C_FLAGS and CMAKE_CXX_FLAGS so we could have different compile options per target. Getting those back means that some rework on that is required.

Could this be solved with -W...... to suppress some (or all) of those warnings?
