### ISSUE TITLE
Modify nf blank application template

### ISSUE THREAD

**Issue by MikroBusNet** [nanoframework/Home#258]
## Suggestion
Add
`while (true)
            {
                Thread.Sleep(200);
            }
`
at the end of _main()_ in the nanoFramework blank application template.

This should prevent users coming from NETMF to use `Thread.Sleep(Timeout.Infinite);` which is not recommended with nf.

**Comment by piwi1263** [comment]
Put the not recommendation as a comment into the template too.

**Comment by MikroBusNet** [comment]
Done.
