### ISSUE TITLE
Add details about underlying RTOS to boot message

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#264]
- This is relevant not only for general information but also to comply with licensing requirements of the RTOS (ChibiOS for example requires that it's made public that it's being used)

**Comment by networkfusion** [comment]
This is cut off in the output window, so it isnt showing all of the necessary details...

![image](https://user-images.githubusercontent.com/11439699/34584442-ab11a908-f193-11e7-9639-22d028a18eca.png)

**Comment by josesimoes** [comment]
That seems to be cut by the old infostring length. This is happening because the VS extension with the new debug library hasn't been published yet.

**Comment by josesimoes** [comment]
VS extension v0.3.8.15 outputs the device capabilities OK
