### ISSUE TITLE
emit error on compile

### ISSUE THREAD

**Issue by AdrianSoundy** [nanoframework/Home#275]
## Details about Problem

When trying to compile a foreach loop with a string the compiler gives the error:-

CSC : error CS7038: Failed to emit module

nanoFramework area (C# code | Visual Studio extension )

## Detailed repro steps so we can see the same problem

1.  Try to compile following sequence
      
   string test = "abc";
   foreach(char c in test)
   {
   }

**Comment by piwi1263** [comment]
Remember this is UWP not NetMf, you can't do it that way. I've run into that too while porting the SSD1306 driver. Try line 307 before doing the foreach loop.

![image](https://user-images.githubusercontent.com/10466039/34693109-c62b5464-f4c2-11e7-92ee-581b5f5ed8ad.png)

**Comment by AdrianSoundy** [comment]
In a desktop UWP app it works.

I found the problem in the end and used a normal for loop which worked

I'll change it to your way as it looks a cleaner solution.

Adrian

**Comment by josesimoes** [comment]
The root cause for this should be an issue with the string enumerator.
In the mean time the workaround suggested by @piwi1263 seems to be the best approach.

**Comment by josesimoes** [comment]
This is happening because `String` doesn't implement `IEnumerable`.
Adding support for this would increase the deployed assembly size.
Because an workaround for this exists, we are better keeping it as it is.

This may change in the future if we decide to add `IEnumerable` implementation to `String`.
