### ISSUE TITLE
Visual Studio extension holds all serial ports open

### ISSUE THREAD

**Issue by AdrianSoundy** [nanoframework/Home#276]
## Details about Problem
When running the Visual Studio Extension it opens and holds open all serial ports in system, even ones that are not detected as running nanoFramework.  

nanoFramework area ( Visual Studio extension  )

VS version (if appropriate): 15.5.4 and previous versions
VS extension version : 0.3.8.18
OS version (i.e. win10 v1607 (14393.321)): Win10

Worked before? If so, with which nanoFramework version: Never worked

## Detailed repro steps so we can see the same problem

1. Start Visual studio with Extension enabled.

2.  Try to open unrelated COM port.

**Comment by josesimoes** [comment]
When a new serial port is detected VS extension connects to it and in order to try to find out if there is a nanoFramework device at the other end.
Right now it's not closing the port after that detection operation thus the serial port is not released.
