### ISSUE TITLE
Serial communication event on incoming/receiving data

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#285]
## Details about missing functionality.

RFC: Serial communication event on incoming/receiving data.
Weigh in at the Slack thread [here](https://nanoframework.slack.com/archives/G4GM0D1BK/p1518683760000313).

**Comment by josesimoes** [comment]
ChibiOS HAL UART has added callback for RX char detection: `_uart_wakeup_rx_cm_isr`
