### ISSUE TITLE
nanoHal is wrongly using a target specific call

### ISSUE THREAD

**Issue by Sirokujira** [nanoframework/Home#286]
Where it is a target-dependent code.
src/HAL/Include/nanoHAL.h

use chHeapAlloc/malloc, chHeapFree/free.
Why is not using the platform_malloc/platform_free function?
(Because different code uses the above function.)

**Comment by josesimoes** [comment]
Hi @Sirokujira. You are correct! Thank you for catching this and reporting it! 👍

**Comment by josesimoes** [comment]
`chHeapAlloc` is to be replaced with  `platform_malloc`
`chHeapFree` is to be replaced with `platform_free`
