### ISSUE TITLE
Remove chibios version from cmake-variants.json

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#295]
## Details about Problem

nanoFramework area (Hardware/target board )

As found with various upgrades, nanoFramework is very dependent on the ChibiOS major version. As such it makes sense to fix the version in code so there is less confusion to the developer.

**Comment by josesimoes** [comment]
This makes perfect sense to me.
So the plan is to:

- [ ] remove the ChibiOS version from the cmake variants and CMake options
- [ ] fix the CMakes to don't care about the version and just grab the official fork
- [ ] remove the ChibiOS version from the cmakevariants.template 
- [ ] remove this option from the documentation here it's showing
