### ISSUE TITLE
Missing assemblies deployment

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#302]
## Details about Problem

When deploying a project that references another project the assemblies, packages of the second (or third or forth) project are not added to the list of asemblies to be deployed.

VS version (if appropriate): Current as of this writing

OS version (i.e. win10 v1607 (14393.321)): N/A

Worked before? If so, with which nanoFrameowrk version: Not detected if ever did work.

## Detailed repro steps so we can see the same problem

1. Create new project and add some package like GPIO or ADC or PWM and some code.

2. Create new project and refer to project in step 1 only. Set project 2 as startup project and start deployment of project created in step 2. The referred assemblies of project one are not in the deployment to the target board.

**Comment by josesimoes** [comment]
Seems to be happening

**Comment by josesimoes** [comment]
@steffalk is waiting for this too

**Comment by steffalk** [comment]
Hello everybody, no urgent problem here. I can wait until this gets fixed and will be happy with it.

Von: José Simões [mailto:notifications@github.com]
Gesendet: Sonntag, 8. April 2018 19:43
An: nanoframework/Home <Home@noreply.github.com>
Cc: Falk, Stefan <Stefan.Falk@ct-systeme.com>; Mention <mention@noreply.github.com>
Betreff: Re: [nanoframework/Home] Missing assemblies deployment (#302)


@steffalk<https://github.com/steffalk> is waiting for this too

**Comment by josesimoes** [comment]
It turns out that the deployment provider isn't able to access the resolved assemblies of referenced projects.
This means that the workaround for this is:
- Set the referenced projects to NOT deploy
- Add the referenced assemblies of referenced project in the main app project so they get deployed.
