### ISSUE TITLE
Incorrect version of assemblies during deploy

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#303]
## Details about Problem
After the deployment of used assemblies of the application, those assemblies do almost always have the version of the application and not the assembly itself.

## Detailed repro steps so we can see the same problem

1. Add one package or more to your application, deploy to target and view in device explorer in the list of assemblies. You'll see the assemblies all are set to 1.0.0.0 only if the application version is set manually this version changes. The assembliy versions do stay on 1.0.0.0 although they are (mostly) of different versions.

**Comment by piwi1263** [comment]
So why can't the extension pick up this info since it is display during deploy time and debug time and put in the output window ... if I understand this correctly we 'just' have to parse the packages.config file:

![image](https://user-images.githubusercontent.com/10466039/38455518-aaf1cc62-3a79-11e8-8c42-85a147a2637c.png)

**Comment by josesimoes** [comment]
What is showing in the assemblies list is coming from the device which has no idea what is packages.config.
As I've tried to explain the device is parsing the deployed assembly version with the custmary version info with format MAJOR.MINOR,REVISION and returns that. In case we need more than that, that return format has to be changed and the parsing too.

**Comment by piwi1263** [comment]
I could be wrong but when lauching in debug the output window state this version info, as it seems coming from the nf extension. So my idea is when the info is avail there, why can't the info be picked up at deploy time. 

![image](https://user-images.githubusercontent.com/10466039/38782441-ba3238bc-40f3-11e8-9a55-a70252887443.png)

**Comment by piwi1263** [comment]
Ok, I've looked a bit deeper and I get your point as you stated above the version information is probably directly retrieved from the assemblies and the ones I've looked at are on 1.0.0.0. Closing this issue.
