### ISSUE TITLE
Update cmake variants doc for random number generation option 

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#305]
The document for the cmake variants file requires to be updated:

The use of random number generation is not on all boards present, although a minority but causes the build to fail.

Since most of the MCUs have support for TRNG ( = True Random Number Generation) when not specifying the default is set to be TRUE, if this needs to be FALSE then it can be done using an additional option:

"USE_RNG" : "FALSE"

The configuration part of the build will report the activation accordingly.

Update to at least the cmake-variants document here [https://github.com/nanoframework/Home/blob/master/docs/building/cmake-tools-cmake-variants.md](url) is required.

**Comment by josesimoes** [comment]
Doc updated with this CMake option and explanation about it.
