### ISSUE TITLE
SD Card support

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#308]
## Details about the missing functionality.

RFC: SD Card Support and the usual file system of course.

**Comment by networkfusion** [comment]
fatfs is already there, it is just the managed side and possibly the driver...

**Comment by networkfusion** [comment]
nanoFramework/lib-windows.storage managed library repo created.

Q: should filesystem be more than SD cards, e.g. USB memory

**Comment by piwi1263** [comment]
@networkfusion: I'd normally expect that yes. FatFs as I've read from the author supports not SD Cards but RAM, USB and the size is not limited to 2 or 4 GB, the limit at the moment is set to 2TB and 4GB on a file basis. And multiple file systems, FAT, FAT32, exFAT.

BUT, it can start off with a minimum so we don't have to wait that long and use it for various tests. And see where the road leads

**Comment by josesimoes** [comment]
I say yes. 
Use cases such "auto-update" from files in the SD Card or USB thumb drive seem a very good reason for having it.

As Peter mentioned too, it seems that with the current driver, that all those are already included for the same, so yes.

**Comment by networkfusion** [comment]
The reason I asked is that we need to be able to mount the file system from the managed side... We just need to factor that in...

**Comment by josesimoes** [comment]
This is starting to look good! 

With the following test app:

```
namespace AccessSDcard
{
    public class Program
    {
        public static void Main()
        {
            // Get the logical root folder for all removable storage devices
            StorageFolder externalDevices = Windows.Storage.KnownFolders.RemovableDevices;

            // list all removable storage devices
            var removableDevices = externalDevices.GetFolders();

            // get folders on SDCard (which should be the 1st device)
            var foldersInSDcard = removableDevices[0].GetFolders();

            Thread.Sleep(Timeout.Infinite);
        }
    }
}
```

I'm able to list the SD Card...
![image](https://user-images.githubusercontent.com/1881520/48633102-81764200-e9ba-11e8-9f7f-4a46531f6cb9.png)


... and retrieve a list with the folders inside it:
![image](https://user-images.githubusercontent.com/1881520/48633111-8804b980-e9ba-11e8-87f4-5e126acb92c1.png)

![image](https://user-images.githubusercontent.com/1881520/48633114-8a671380-e9ba-11e8-96f7-b9a29ea523e6.png)

**Comment by josesimoes** [comment]
We now have support for SD Card on all targets: STM32 and ESP32.
