### ISSUE TITLE
PWM does not allow "inverted output"

### ISSUE THREAD

**Issue by MikroBusNet** [nanoframework/Home#322]
## Details about Problem
The current driver does not allow inverted output (or "active low output") for PWM. Or, said differently : you can't change the pin polarity in the managed code.

This is "by design" at the moment, because of the way ChibiOS is handling this feature. Indeed, this is declared in the _PWMConfig_ structure, which is initialized in the object that represents the UWP **controller**.  But, in the UWP API, the output waveform is set in the **PwmPin** class (_SetPolarity()_ method).

Excerpt from the native driver :
```
PWMConfig pwmConfig = 
        {
            desiredFrequency*period,            // PWM clock frequency
            period,                             // PWM period
            NULL,                               // No callback
            // Enable all channels
            {
                {PWM_OUTPUT_ACTIVE_HIGH, NULL},
                {PWM_OUTPUT_ACTIVE_HIGH, NULL},
                {PWM_OUTPUT_ACTIVE_HIGH, NULL},
                {PWM_OUTPUT_ACTIVE_HIGH, NULL}
            },
            0,
            0
        };
```
You can see that the output waveform is set at the same level as the output frequency. It has been set to _Active high_ by default as it is the most common use of Pwm.

This will need a major rewrite of the driver because acting on the PWMConfig may need to stop the current execution of Pwm pins that are running. Hence the "2nd preview" milestone.

**Comment by josesimoes** [comment]
This was never implemented IIRC... Feel free to open a new issue with the suggestion, if that's important to you.
