### ISSUE TITLE
SpiDevice.FromId() fails on second device in the same bus

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#323]
nanoFramework area:  Windows.Devices.Spi

Worked before? No

## Detailed repro steps so we can see the same problem

1. Instantiate an SpiDevice on a bus

2. Instantiate another SpiDevice on the same bus

## Analysis 

The current implementation of the SpiDevice constructor is reusing the existing one whenever the same Id already exists. Which is wrong.

**Comment by MikroBusNet** [comment]
It worked before.

**Comment by MatthiasJentsch** [comment]
You run the following code:
```
SpiConnectionSettings settingsDevice1 = new SpiConnectionSettings(22);
settingsDevice1.ClockFrequency = 1000000;
SpiDevice.FromId("SPI1", settingsDevice1);
SpiConnectionSettings settingsDevice2 = new SpiConnectionSettings(21);
settingsDevice2.ClockFrequency = 1000000;
SpiDevice.FromId("SPI1", settingsDevice2);
```
If it's deployed into the device and the visual studio debugger is not attached it's working. But if this code is running in debugger you will get a System.ArgumentException in NativeInit() during the second call of SpiDevice.FromId.
So it seems to me that this is an issue only if you run in the debugger.

**Comment by josesimoes** [comment]
Just tested this on STM32F429I-Disco and it's working. 
Fixed in ESP32 too.
