### ISSUE TITLE
"nanoFramework ESP32 firmware flasher" does not download esptool.zip

### ISSUE THREAD

**Issue by Octoate** [nanoframework/Home#326]
If you download the "nanoFramework ESP32 firmware flasher.exe" from the releases page here on GitHub (at this time https://github.com/nanoframework/nf-tools/releases/tag/v1.0.13) and start it in a dedicated directory, the application crashes because it cannot find the "esptool.zip" file. For the ease of use, it either should be released as a ZIP archive that contains the flash tool and the esptool or the flasher should automatically download the latest version of the esptool if the file does not already exist.

## Detailed repro steps so we can see the same problem
1. Create an empty directory
2. Download the flasher from https://github.com/nanoframework/nf-tools/releases/tag/v1.0.13 and save it in the created directory
3. Start the flasher
4. Enter a correct serial port name for the ESP32
5. The flasher crashes, because it cannot find the "esptool.zip"

**Comment by MatthiasJentsch** [comment]
When PR https://github.com/nanoframework/nf-tools/pull/9 will be merged that bug is fixed.
