### ISSUE TITLE
Add details about reference boards in knowledge base

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#348]
The pages of the reference targets in the knowledge base are missing a lot of details, such as:
- what nF APIs are available in the pre-built images (this is already mentioned in the home page)
- what is exposed/configured (ADC, PWM, etc)
- floating point support
- memory available: heap for managed apps and deploy area size 

These are linked from [here](http://docs.nanoframework.net/articles/reference-targets-intro.html).

**Comment by microDevSys** [comment]
is there a new link ? http://docs.nanoframework.net/articles/reference-targets-intro.html is dead

**Comment by josesimoes** [comment]
Where did you get this URL?

**Comment by networkfusion** [comment]
@josesimoes  ![image](https://user-images.githubusercontent.com/11439699/103950577-068db980-5135-11eb-820b-0f7d6ae10ae6.png)

**Comment by josesimoes** [comment]
These are mostly complete now.
