### ISSUE TITLE
Missing STM469/479 ifdef Checks in Memory and PWM Driver Files

### ISSUE THREAD

**Issue by gligorov** [nanoframework/Home#352]
The memory and PWM drivers are missing the declarations to include the 469/479 MCUS, and they are pin and port compatible with the MCUS already included. 
<br/><br/>
How to Reproduce/See:<br />
To see the problem simply select the Discovery 429 board, and in the board file change the MCU to STM32F469xx, then build, and it will fail.
<br/><br/>
I have found the following locations in these files need to ne updated to allow building a target with board that has  STM32F469  or STM32F479.
<br/><br/>
**nanoCLR/Windows.Devices.PWM/win_dev_pwm_native_Windows_Devices_Pwm_PwmPin.cpp**  

line 20 needs to be:  #if defined(STM32F427xx) || defined(STM32F429xx) || defined(STM32F469xx)
<br/><br/>
**nf-overlay/os/hal/include/stm32_fsmc/hal_stm32_fsmc.h**   
lines, 19, 69, 148,203,222, 303, need to have:    	 defined(STM32F469xx) || defined(STM32F479xx) || \
<br/><br/>
**nf-overlay/os/hal/ports/STM32/LLD/FSMCv1/fsmc_sdram_lld.c**

line 11 needs 	 defined(STM32F469xx) || defined(STM32F479xx) || \
<br/><br/>
**nf-overlay/os/hal/ports/STM32/LLD/FSMCv1/fsmc_sdram_lld.h**

line 12 needs 	 defined(STM32F469xx) || defined(STM32F479xx) || \
<br/><br/>
**nf-overlay/os/hal/ports/STM32/LLD/FSMCv1/fsmc_sram_lld.c**

line 109 needs 	 defined(STM32F469xx) || defined(STM32F479xx) || \
 <br/><br/>
**nf-overlay/os/hal/src/stm32_fsmc/hal_stm32_fsmc.c**

 line 70 needs 	 defined(STM32F469xx) || defined(STM32F479xx) || \
<br/><br/>
After these changes, I am able to build a board that is based on Disco429, but has STM32F469xx on it. I am still in early development but hope this will help to get the 469 MCUs included. I hope to contribute once I get to know the project better.

**Comment by josesimoes** [comment]
Thanks for providing this fix. 👏 
Can I ask you to submit a PR with it? Please follow the contribution guideline (in case you're not familiar with GitHub process for doing it 😉 )

And, of course, looking forward for your next contributions!
