### ISSUE TITLE
Add flag to capabilities to report if target has booter or not

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#358]
STM32 targets have booter, ESP32 doesn't. Knowing if a target has booter is important to know how to proceed with firmware updates, for example.

**Comment by MatthiasJentsch** [comment]
Does the ESP32 have no booter? We have the file bootloader.bin that we flash into the device. Is that not the booter? Or do we mean with "booter" another thing?

**Comment by josesimoes** [comment]
ESP32 has its own booter which is not the nanoFramework one.
@AdrianSoundy can provide more details on this.
