### ISSUE TITLE
Class library references locked after deploy 

### ISSUE THREAD

**Issue by AdrianSoundy** [nanoframework/Home#361]
When a project references a class library. 

After deploy it is always locked until Visual Studio is restarted.

Included blinky solution example for testing.

To reproduce:-
- Build project
- Deploy project
- ReBuild project
The class library will be locked.

[BlinkTestSolution.zip](https://github.com/nanoframework/Home/files/2197072/BlinkTestSolution.zip)

Tested on Esp32

**Comment by josesimoes** [comment]
@piwi1263 and @steffalk I believe you were suffering from this too... 😉
