### ISSUE TITLE
I2C read not working with EEprom

### ISSUE THREAD

**Issue by Dweaver309** [nanoframework/Home#364]
## Details about Problem

nanoFramework area (Hardware/target board)

VS version (if appropriate):

target: ESP32

## Detailed repro steps so we can see the same problem

Read operation is not returning the expected result.

### Sample Project (if applicable)
(see bellow)

**Comment by Dweaver309** [comment]
[EEprom.driver.zip](https://github.com/nanoframework/Home/files/2202508/EEprom.driver.zip)

More information:
https://nanoframework.slack.com/messages/C4MGGBH1P/convo/C4MGGBH1P-1531755978.000562/

**Comment by Dweaver309** [comment]
This code in .netmf is working:
https://github.com/Dweaver309/i2cBus/blob/master/i2cBusSourceCode/CSharp/Program.cs

**Comment by AdrianSoundy** [comment]
Had a look at the datasheet and the provided code.

The writebyte() function looks ok but the readbyte() is wrong.
The Read random has to be done as 2 operations:-
1) Set the Address
2) Read next byte(s)
Seen in this from datasheet as it has to start bytes.

![readrandom](https://user-images.githubusercontent.com/22250953/42844554-6a5b5fea-8a67-11e8-9101-eaedab65f806.png)

So the code for ReadByte needs to be:-

EEprom.Write(new[] { (Byte)(Address >> 8), (Byte)(Address & 0xFF) });
EEprom.Read(Data);

The Read will read as many bytes as the length of the byte[].

**Comment by Dweaver309** [comment]
Good Morning Adrian, I may have it working. The first issue was the delay between the write and read statements. The second seems really strange but defining a string to send works but sending a quoted string does not. Example: String str = "This is an EEprom test for ESP32.";
           EEprom24LC256.Write(EEprom24LC256.Address.TestWrite, str);

This does not work:  EEprom24LC256.Write(EEprom24LC256.Address.TestWrite, "This is an EEprom test for ESP32.");?????

I am still testing but I think it is working. I will clean up the working code and post. I am not sure the issues above are accurate but with the changes I think it will work. Thanks to everyone who helped!!!
