### ISSUE TITLE
Add startup guide for STM32 devices requiring DFU

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#370]
Update the guide [here](http://docs.nanoframework.net/articles/getting-started-guides/getting-started-managed.html) to include a description for devices using DFU.

Markup document [here](https://github.com/nanoframework/nanoframework.github.io/blob/pages-source/articles/getting-started-guides/getting-started-managed.md).

Split the section "uploading the firmware on the board" in two: 
- one for the STlink process (which is already there) 
- add a new sub-section for DFU 

A sentence with a general explanation to give some guidnace and context to the developer reading it, would be most helpful.

**Comment by josesimoes** [comment]
Suggestions:
- Add another section in "The hardware" explaining that this tutorial will address the STM32 based targets with details for using ST-Link and DFU, depending on the target availability.
- Similarly in "Uploading the firmware to the board"

**Comment by josesimoes** [comment]
@Dweaver309 added this [guide](https://github.com/Dweaver309/UpdateFirmware/blob/master/UpdateFirmware.pdf) to its repo

guess  that can be a good starting point to write our own. 😉 
Guess a bit of copy/paste won't cause any hard feelings.... 😁

**Comment by Dweaver309** [comment]
[How to update firmware.zip](https://github.com/nanoframework/Home/files/2332320/How.to.update.firmware.zip)
This is the original document use it anyway you want.  I hope it helps!

**Comment by Dweaver309** [comment]
@Dweaver309 I will update the issue.

**Comment by Dweaver309** [comment]
I think I sent the changes for this?
https://github.com/nanoframework/nanoframework.github.io/blob/pages-source/articles/getting-started-guides/getting-started-managed.md#uploading-the-firmware-to-the-board

**Comment by Dweaver309** [comment]
[create-dfu-file.zip](https://github.com/nanoframework/Home/files/2788239/create-dfu-file.zip)
If the Pull Request didn't make it here are the changes. Thanks for the help

**Comment by josesimoes** [comment]
Completed with nanoframework/nanoframework.github.io#15.
