### ISSUE TITLE
Encoding.UTF8 is missing GetString(byteArray)

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#376]
nanoFramework area (class library)

This is very handy in HTTP use case scenarios.

**Comment by piwi1263** [comment]
Although probably not handy but you could try:

**Encoding.UTF8.GetDecoder().Convert(data, 0, data.Length, _chars, 0, data.Length, false, out int _bytesUsed, out int _charsUsed, out bool _completed);
string tmp = new String(_chars, 0, _charsUsed).Trim('\r', '\n');**

**Comment by josesimoes** [comment]
Right now I'm using this workaround:

`new String(Encoding.UTF8.GetChars(buffer))`  😉
