### ISSUE TITLE
nanoFramework properties missing

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#382]
When lauching a nanoFramework library project in VS 2017 15.8.0 the nanoFramework properties are not displayed anymore in the property pages of the project.

Using extension 0.5.0.24.

**Comment by josesimoes** [comment]
Confirmed.

**Comment by josesimoes** [comment]
This seems to be caused by a recent change in the "new" project system.
Investigating the root cause.

**Comment by josesimoes** [comment]
Ask about this in VS Project Gitter. Seems that we are not alone with this.

**Comment by josesimoes** [comment]
⚠️  currently the only available workaround is to manually edit the nfproj file and add/change the properties as needed ⚠️

**Comment by josesimoes** [comment]
nanoFramework project properties are now available in the Properties view for the project.
