### ISSUE TITLE
Math.Floor(float) hangs/resets the board on Netduino 3

### ISSUE THREAD

**Issue by steffalk** [nanoframework/Home#387]
VS version: VS 2017 15.8.1
OS version: Windows 10 1803 17134.228
VS extension version: 0.5.0.28
Firmware version: preview-776

This worked about 2 months ago.

## Detailed repro steps so we can see the same problem

1. Create a nanoFramework solution:

`
using System;

namespace NFAppTestMathHang
{
    public class Program
    {
        public static void Main()
        {
            Console.WriteLine("Hello world!");

            float x;

            x = Math.Round(5.5f); // <-- works after Jose´s fix.

            x = Math.Floor(5.5f); // <-- hangs here to the point that the board must be re-flashed!

            Console.WriteLine(x.ToString()); // <-- never arrives here
        }
    }
}
`

2. Run it on the board. The board hangs on Math.Floor.

**Comment by josesimoes** [comment]
Nice catch! (oh how we need unit testing 😢  )

BTW, most of the other math methods would cause this too. I've rework the math calls to fix it for all calls.
