### ISSUE TITLE
object.GetHashCode not working

### ISSUE THREAD

**Issue by MatthiasJentsch** [nanoframework/Home#390]
## Details about Problem

nanoFramework area: nanoCLR

Worked before? I think no.

## Detailed repro steps so we can see the same problem

Write this C# program:

```
object a = new object();
object b = new object();
object c = a;
int ha = a.GetHashCode();
int hb = b.GetHashCode();
int hc = c.GetHashCode();
```
And all three (ha, hb and hc) are zero. GetHashCode returns alsways zero.
Tested with Prewiew 791 on an ESP32.

**Comment by MatthiasJentsch** [comment]
That's not working because ```object``` has no fields. It's also not working for all instances that has no fields.

**Comment by josesimoes** [comment]
After some investigation I'm tempted to suggest that we should leave it as it is.

See the official docs [here](https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?redirectedfrom=MSDN&view=netframework-4.7.2#remarks)
The hash code of object shoul **NOT** be used as unique object identifier for hashing purposes.

Also about the native implementation [here](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.gethashcode?view=netframework-4.7.2).

**Comment by josesimoes** [comment]
Any other thoughts on this? 😉

**Comment by NemesisXB** [comment]
Even though it should not be used as a unique object identifier, won't it be better to at least have it work like the standard implementation?
Otherwise, should it not at least throw not implemented?

**Comment by josesimoes** [comment]
OK. Digging deeper I could find an old native implementation for this call [here](https://web.archive.org/web/20100826100454/http://www.koders.com/cpp/fid187B41425FAF5DEC8C7921012C309DC6534FE487.aspx#L90)


Guess we can try to accomplish something similar for objects, instead of relying on calculating the hash from fields. Or, perhaps, if there are no fields then return the CRC32 of the heap block address?

**Comment by MatthiasJentsch** [comment]
I think calculating the hash of the fields is in general a good idea. Implementing a complicated algorithm would waste memory and time. I thinks we should improve what we have and return the CRC32 of the heap block address if the instance has no fields.

**Comment by josesimoes** [comment]
Suppose we have an agreement on this. Let's go for it
