### ISSUE TITLE
ToString() causing hardfault

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#416]
## Details about Problem

nanoFramework area (Hardware/target board )

## Detailed repro steps so we can see the same problem

1. The following code causes a hard fault on STM32
`((long)-1234567899876543210).ToString("X16")`

**Comment by sharmavishnu** [comment]
#### Additional Information
Performed a few tests on .NET Core 2.0 and nanoFramework. (This test was performed on build using files from repo on 9-Oct-18 and tried on STM32F401RE Nucleo board). Here are the results. See if this helps:

**Test 1**
*.NET Core 2.0*
long test = 32769;
string asStr = test.ToString("X7");
//String returned is 0x0008001 -- Correct

*nanoFramework*
long test = 32769;
string asStr = test.ToString("X7");
//String returned is 0x8001000 -- Incorrect

**Test 2**
*.NET Core 2.0*
long test = 64435;
string asStr = test.ToString("X8");
//String returned is 0x0000FBB3 -- Correct

*nanoFramework*
long test = 32769;
string asStr = test.ToString("X8");
//String returned is 0xFBB30000 -- Incorrect

**Test 3**
*.NET Core 2.0*
long test = 4294967294;
string asStr = test.ToString("X8");
//String returned is 0xFFFFFFFE -- Correct

*nanoFramework*
long test = 4294967294;
string asStr = test.ToString("X8");
//String returned is 0xFFFFFFFE -- Correct

**Test 4**
*.NET Core 2.0*
long test = 4294967294;
string asStr = test.ToString("X9");
//String returned is 0x0FFFFFFFE -- Correct

*nanoFramework*
long test = 4294967294;
string asStr = test.ToString("X9");
//String returned is 0xFFFFFFFE0 -- Incorrect

**Test 5**
*.NET Core 2.0*
long test = 4294967294;
string asStr = test.ToString("X10");
//String returned is 0x00FFFFFFFE -- Correct

*nanoFramework*
long test = 4294967294;
string asStr = test.ToString("X10");
//Debugger hangs...causes hardfault. Only way to recover is to re-flash hex files
