### ISSUE TITLE
Windows.Devices.Wifi AvailableNetworksChanged event breaks by adding reference to m2mqtt

### ISSUE THREAD

**Issue by ankur198** [nanoframework/Home#427]
If using `m2qtt` and `windows.devices.wifi` simultaneously then `WifiAdapter.AvailableNetworksChanged` will never trigger. I noticed while debugging that `WifiAdapter.NetworkReport` was populated but event never triggered

**nanoFramework area:** Nuget packages

**Firmware image version:** 1.0.2-preview.23

### Detailed repro steps so we can see the same problem

1. [https://github.com/nanoframework/Samples/tree/master/Wifi](https://github.com/nanoframework/Samples/tree/master/Wifi) -get this project

2. [https://github.com/AdrianSoundy/paho.mqtt.m2mqtt/tree/nanoframework](https://github.com/AdrianSoundy/paho.mqtt.m2mqtt/tree/nanoframework) add reference from this project

**Comment by josesimoes** [comment]
User has reported that this was solved after properly update the references and NuGets.
