### ISSUE TITLE
Is there a GUI framework here? like emwin,ucgui,touchgfx

### ISSUE THREAD

**Issue by snikeguo** [nanoframework/Home#435]
RT .
THX

**Comment by josesimoes** [comment]
Hello!

Currently there isn't support for any GUI framework in nanoFramework. Hopefully that can change soon, but we don't have an availability date.

If you are up to it, maybe you can contribute with some work towards that? It would be a nice addition to the framework!

**Comment by josesimoes** [comment]
Closing this after answering the question and no follow-up from the user.
