### ISSUE TITLE
Developer guide is empty

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#442]
On the home page there is a link to developer guide:
![image](https://user-images.githubusercontent.com/11439699/50045652-a54aa780-008e-11e9-9313-4ac2b0068cb8.png)

But it is a dead link...
![image](https://user-images.githubusercontent.com/11439699/50045625-09b93700-008e-11e9-9128-d487f92eec4e.png)

**Comment by josesimoes** [comment]
Yes... this one an a couple of others never got filled with meaningful content...
Care to delete them and remove the link(s)?

**Comment by networkfusion** [comment]
no longer relevant (must have been fixed).
