### ISSUE TITLE
Add support for GCC 8.2.1

### ISSUE THREAD

**Issue by piwi1263** [nanoframework/Home#443]
### Detailed repro steps so we can see the same problem

1. Install GCC 8.2.1
2. Point the cmake-variants.json entry for "TOOLCHAIN_PREFIX" to your installed directory
3. Clean the build folder and perform a build
4. Compiler reports that option -mstructure-size-boundary=8 is depricated
5. Remove that option in the used MCU CMake/Modules/CHIBIOS_STMF?xx_GCC_options.cmake file
6. Clean your build folder
7. Build again 
8. Another error in a misalignment when trying to generate a nanoBooter image.

P.S. Find attached a full log of the compiling with the corrected option and the result thereof.
[vsc_build_f439zi_821.log](https://github.com/nanoframework/Home/files/2725202/vsc_build_f439zi_821.log)

**Comment by piwi1263** [comment]
A bug report on having the same behavior can be found on https://bugs.launchpad.net/gcc-arm-embedded/+bug/1810274

**Comment by piwi1263** [comment]
Using a work around the objcopy error is gone but another error occurred. Please view the 2. log for details.
[vsc_build_f439zi_821_2.log](https://github.com/nanoframework/Home/files/2729539/vsc_build_f439zi_821_2.log)

**Comment by josesimoes** [comment]
This new error it totally unrelated. There seems to be a real issue with the declaration of the cast of those calls... Surprised this is there for so long unnoticed! Perhaps this is a proof that the compiler is getting better ... 😉

**Comment by piwi1263** [comment]
Another step, hopefully closer to the solution 
https://sourceware.org/bugzilla/show_bug.cgi?id=24065

**Comment by piwi1263** [comment]
The root cause seem to be fixed but as stated [here](https://sourceware.org/bugzilla/show_bug.cgi?id=24065) which (new) version of an ARM GNU release will include the fix is not known ... yet

**Comment by networkfusion** [comment]
8-2019-q3-update is now available
