### ISSUE TITLE
SPI module malfunctioning with ST type boards

### ISSUE THREAD

**Issue by Dweaver309** [nanoframework/Home#447]
### Details about Problem

**nanoFramework area:** (C# code)

**VS version:** 

**VS extension version:** 

**Target:** 

**Firmware image version:** 

**Device capabilities output:** 

Worked before? If so, with which nanoFramework image version: 

### Detailed repro steps so we can see the same problem

See bellow

### Sample Project (if applicable)

See bellow

**Comment by Dweaver309** [comment]
I am trying the create a spi device on a Netduino 3 wifi board. 

The first time I run the sample program in VS the spi device is created. 

The next time I run the program it stops on the line:
 
_TestSPIDevice = SpiDevice.FromId("SPI2", connectionSettings) 

No error is given the application justs stops.

If I erase the application area and toggle power the spi device is created again.

Is there an issue with the spi module or is there something I need to put in my code?

[Program.zip](https://github.com/nanoframework/Home/files/2802558/Program.zip)

**Comment by josesimoes** [comment]
@Dweaver309 it would be great if you could follow the issue template in future issues... it's there to help developers reporting issues and for the team to "parse" it more efficiently 😉

**Comment by josesimoes** [comment]
Is this still an issue?

**Comment by Dweaver309** [comment]
I think is issue has been corrected. I moved my project to an ESP32 board that works as intended.  I have seen code on Discord that is working. I am closing this issue.
