### ISSUE TITLE
ST_STM32F769I_DISCOVERY - Questions

### ISSUE THREAD

**Issue by Korporal** [nanoframework/Home#451]
Hi,

I'm very interested in getting my hands on nanoframework and it seems that the STM32F7691 Discovery is a good choice. However I can't tell whether I'd be able to use WiFi with this or not. It also seems that WiFi requires a "daughter board" so does anyone here know anything about that? where to get it? does it require its own special firmware or anything? Is WiFi with this board something others here have used/tried?

All I can find when I search the web about this board and Wi-Fi are repeats of this phrase form the manufacturer's documentation:

"Wi-Fi or Ext-EEP daughterboard connector"

Thx

**Comment by josesimoes** [comment]
As far as I know the board has an extension that you can use to add boards on top of it. I'm not aware of specific Wi-Fi daughter board...

Currently the nanoFramework image that is provided for this board has network capabilites though Ehernet connection.

Wi-Fi options are available in the ESP32_WROOM_32 reference target.
