### ISSUE TITLE
Using "Detach All" when debugging leads to VS locking files and preventing rebuild.

### ISSUE THREAD

**Issue by Korporal** [nanoframework/Home#454]
### Details about Problem

**nanoFramework area:** ( CLR?)

**VS version: 2017 v15.9.6** 

**VS extension version: 1.0.3.32** 

**Target: STM32F7 DISCO Board with LCD** 

**Firmware image version: ST_STM32F769I_DISCOVERY-1.0.3** 

**Device capabilities output:** 

> 
> 
> 
> System Information
> HAL build info: 1.0.3.230, nanoCLR running @ ST_STM32F769I_DISCOVERY built with ChibiOS v18.2.1.2
> 
> Image build @ Dec 17 2018 GNU ARM GCC v7.3.1
> 
> OEM Product codes (vendor, model, SKU): 0, 0, 0
> 
> Serial Numbers (module, system):
>   00000000000000000000000000000000
>   0000000000000000
> 
> Solution Build Info: 1.0.3.230, nanoCLR running @ ST_STM32F769I_DISCOVERY built with ChibiOS v18.2.1.2
> 
> AppDomains:
> 
> Assemblies:
>   NFApp1, 1.0.0.0
>   nanoFramework.Hardware.Stm32, 1.0.2.2
>   mscorlib, 1.1.0.4
>   nanoFramework.Runtime.Events, 1.0.2.2
>   Windows.Devices.Gpio, 1.0.2.2
> 
> Native Assemblies:
>   mscorlib v1.1.0.4, checksum 0x7CCFBEC1
>   nanoFramework.Runtime.Native v1.0.2.2, checksum 0xFE14C7A7
>   nanoFramework.Hardware.Stm32 v1.0.2.2, checksum 0xFFC9E917
>   nanoFramework.Devices.Can v1.0.1.2, checksum 0xD2E9416A
>   nanoFramework.Devices.OneWire v1.0.1.2, checksum 0x4BFAF309
>   nanoFramework.Networking.Sntp v1.0.2.2, checksum 0x733B4551
>   nanoFramework.Runtime.Events v1.0.2.2, checksum 0xBFF88292
>   EventSink v1.0.0.0, checksum 0xF32F4C3E
>   System.Math v1.0.2.2, checksum 0x4BDCF00F
>   System.Net v1.0.2.2, checksum 0xFD8EBD9C
>   Windows.Devices.Adc v1.1.0.2, checksum 0xD21F3E86
>   Windows.Devices.Gpio v1.0.2.2, checksum 0xF8E84C07
>   Windows.Devices.I2c v1.1.0.2, checksum 0x0C4EA1B2
>   Windows.Devices.Pwm v1.1.0.2, checksum 0x84B1FBF8
>   Windows.Devices.SerialCommunication v1.0.2.17, checksum 0x093798D6
>   Windows.Devices.Spi v1.1.0.2, checksum 0x3DE083A4
> 
> 
> 
> --------------------------------
> ::        Memory Map          ::
> --------------------------------
> Type     Start       Size
> --------------------------------
> RAM    0xc0000000  0x01000000
> FLASH  0x08000000  0x00200000
> 
> 
> 
> -----------------------------------------------------------
> ::                   Flash Sector Map                    ::
> -----------------------------------------------------------
>   Region     Start      Blocks   Bytes/Block    Usage
> -----------------------------------------------------------
>       0    0x08000000       1      0x008000     nanoBooter
>       1    0x08008000       1      0x008000     Configuration
>       2    0x08010000       2      0x008000     nanoCLR
>       3    0x08020000       1      0x020000     nanoCLR
>       4    0x08040000       1      0x040000     nanoCLR
>       5    0x08080000       6      0x040000     Deployment
> 
> 
>  Start        Size (kB)           Usage
> --------------------------------------------
>  0x08000000   0x008000 (32kB)     nanoBooter
>  0x08008000   0x008000 (32kB)     Configuration
>  0x08010000   0x070000 (448kB)    nanoCLR
>  0x08080000   0x180000 (1536kB)   Deployment
> 
> 
> 
> Deployment Map
> Empty
> 

### Detailed repro steps so we can see the same problem

Simply begin to debug some simple app and then in VS use Debug->Deatch All. Try to rebuild the app and it fails unless one restarts VS.

**Comment by josesimoes** [comment]
In order to end a debug session a developer is supposed to use the STOP. Not detach all because the debug isn't started from an attach to process, rather form a "clean start".

The processes that are created for the debugger engine aren't being closed/terminated and - because they are locking the executable for their use - prevent any following attempt to delete the file.


A simple approach to take care of this this would be to disable the "attach to process" and/or "detach all" commands from VS. Not sure if that's possible but it should be investigated. 
Adding this to the backlog hoping that someone can take a look into it.

**Comment by josesimoes** [comment]
Turns out that we can't mess up with VS command buttons. Closing this.
