### ISSUE TITLE
URL Link not working on new sample page

### ISSUE THREAD

**Issue by Dweaver309** [nanoframework/Home#456]
Please read the following information before posting the issue.

## Before posting the issue...

If you need clarification on something, need help on a particular situation or want to start a discussion, instead of opening an issue it is best to start a conversation on one of our Discord channels. 
Go there and select the channel that's most appropriate to the context so subject matter experts are most likely to answer promptly.
You can join our lively [Discord community](https://discordapp.com/invite/gCyBu8T)

:exclamation: Remove the content above here and fill out details below. :exclamation:

### Details about Problem

**nanoFramework area:** (C# code | Visual Studio extension | Hardware/target board | Nuget packages | Community targets | Community contributions | Documentation )

**VS version:** 

**VS extension version:** 

**Target:** 

**Firmware image version:** 

**Device capabilities output:** 

Worked before? If so, with which nanoFramework image version: 

### Detailed repro steps so we can see the same problem

1. 

2.

...

### Screenshot (if applicable/relevant)

The WiFi link on the updated sample page needs to be updated. The current link is
https://github.com/nanoframework/Samples/blob/master/samples/WiFi

The link needs to be updated to 
https://github.com/nanoframework/Samples/tree/master/samples/Wifi

The updates look great!

**Comment by josesimoes** [comment]
Could you please fix that right on GitHub? 

PS: Please respect the issue template or at least remove it. As it's above is rather confusing... Wouldn't you agree?
