### ISSUE TITLE
Inexplicable deploy problem

### ISSUE THREAD

**Issue by Korporal** [nanoframework/Home#459]
If low level tech detail are required I can provide them but basically I updated a simple STM32 DISCO project that ran OK, by adding a Nuget package for Serial IO:

![image](https://user-images.githubusercontent.com/12262952/52984726-e2445a80-33ad-11e9-9942-d1f2dd4f695f.png)

Left is before, right is after.

The when I try to deploy I see:
![image](https://user-images.githubusercontent.com/12262952/52984778-1586e980-33ae-11e9-8f33-21cc97f77c62.png)

I relied on the Nuget system to alert me to what packages to update etc and I have no idea what I must do to address the issues reported.

**Comment by josesimoes** [comment]
According to the message on the output there, basically you are referencing NuGet packages whose versions are not supported in the firmware that's running on your device.

The message content is trying to help you by describing the versions mismatches. 
If you pull the device's capabilities it has a list of the various assemblies it supports along with the versions. You have to reference the corresponding NuGets.

**Comment by josesimoes** [comment]
Closing as there is no further input from the developer.
