### ISSUE TITLE
Visual Studio 2017 extension package did not load correctly

### ISSUE THREAD

**Issue by DeHaanSoftware** [nanoframework/Home#466]
After installing the vsix and restarting Visual Studio 2017 I get the message "The nanoFramework package did not load correctly". See attached screen shot
![NanoFrameWork](https://user-images.githubusercontent.com/12594442/54676947-2e480380-4b02-11e9-90f2-4e96f99b69e8.JPG)

Visual Studio 2017 Community 2017 version 15.9.9 
Tried on both my Windows 10 laptop and my Windows 7 64-bit desktop

**Comment by josesimoes** [comment]
@DeHaanSoftware could you please attach VS activity log (pointed in the error message).

BTW, the extension won't work on Windows 7 because of the USB UWP API that the debugger library uses.

**Comment by DeHaanSoftware** [comment]
Thaks for the comment. So Windows 7 can't be used. Windows 10 works fine now after updating to the latest VS2017 version.

**Comment by tatianilima** [comment]
I experienced the same error with Windows 11 and Visual Studio 2022. 
![nanoFramework_VS](https://user-images.githubusercontent.com/10242154/230785886-63f572b4-fb4c-4c31-be36-a081a221f980.jpg)

Does anyone know how to solve it?

**Comment by Ellerbach** [comment]
The latest version has an issue, please use the one before.
