### ISSUE TITLE
Changing string value during debugging results in string of spaces

### ISSUE THREAD

**Issue by dlkay0** [nanoframework/Home#469]
### Details about Problem

**nanoFramework area:** Visual Studio extension

**VS version:** 15.9.10

**VS extension version:** 1.0.3.92

**Target:** ESP-32

**Firmware image version:** 1.0.4.390

**Device capabilities output:** N/A

### Detailed repro steps so we can see the same problem

1. Assign a string in code
2. Set a breakpoint after that line
3. Edit the value in the Locals/Autos or Hover-over editor (use something other than spaces)
4. Observe the new value is the correct length but only spaces

(Editing numbers seems fine.)

### Screenshot (if applicable/relevant)
![image](https://user-images.githubusercontent.com/12534377/55200285-bb323300-517a-11e9-81d4-f0bdc376f105.png)

**Comment by josesimoes** [comment]
Can't reproduce this... Tried on VS2017 and VS2019. VS extension v2017/2019.2.2.28.
See below. The edited string was also showing correctly at the autos windows.

Feel free to reopen with more data to allow reproducing this, if its still an issue.


![string debug edit](https://user-images.githubusercontent.com/1881520/93802091-e9db7d80-fc3a-11ea-8d9d-6acdf65b93ab.png)
