### ISSUE TITLE
Class library's can not be referenced 

### ISSUE THREAD

**Issue by Dweaver309** [nanoframework/Home#475]
### Details about Problem

**VS version Microsoft Visual Studio Community 2019 RC Version 16.0.0** 

**VS extension version 1.0.0.105** 

**Firmware image version 1.0.4-preview.404** 

### Detailed repro steps so we can see the same problem

1. Built the class library

2. Create a new application

3. Reference the .dll created  

4. The reference  will not be available

### Sample Projects

[NFClassLibrary2.zip](https://github.com/nanoframework/Home/files/3085663/NFClassLibrary2.zip)
[TestClsLib.zip](https://github.com/nanoframework/Home/files/3085664/TestClsLib.zip)

 

...

**Comment by Dweaver309** [comment]
I know nothing about vsix extensions.  However I looked at in earlier NF extension and the newest one. I saw that this version had an extra directory named CSharp.ResourceTemplate.  I hope this helps.
![Missing_Resource_Template](https://user-images.githubusercontent.com/16384668/56370849-98b39880-61c1-11e9-8f52-b6cd053c7366.png)

**Comment by josesimoes** [comment]
I'm afraid that's totally unrelated...
That's the new template for managed resources that was added a few weeks ago.

**Comment by Dweaver309** [comment]
Thanks that is what I thought.

**Comment by Dweaver309** [comment]
The class library's that are referenced can't be viewed in the object browser.

**Comment by josesimoes** [comment]
Reproduced. It works on VS2017, but not on VS2019.
Something must be missing related with a configuration that as to be requested for nF project type.

As a side note: VS Object explorer can't load the referenced libraries when double clicking, not navigate to the objects using F12.

**Comment by josesimoes** [comment]
The root cause for this seems to be with VS Intellisense engine.

Reported the issue on the developer community [here](https://developercommunity.visualstudio.com/content/problem/558572/intellisense-issue-with-referenced-assembly.html). Waiting for feedback.

**Comment by josesimoes** [comment]
Probably solved with microsoft/msbuild#4348.
Need to wait for VS 2019 v16.2 for confirmation.

**Comment by networkfusion** [comment]
Now available in the preview release. Waiting for the official release before this can be closed.

**Comment by josesimoes** [comment]
@networkfusion you have the preview installed and it's working now?

**Comment by networkfusion** [comment]
@josesimoes oops, no, but Preview 4 has just been released which closes 4348?!

**Comment by josesimoes** [comment]
Move from VS Community to GitHub dotnet/project-system#5239

**Comment by networkfusion** [comment]
not sure if this helps yet... but adding for reference: https://referencesource.microsoft.com/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/14.0/bin_/amd64/Microsoft.CSharp.Core.targets
