### ISSUE TITLE
Missing device explorer window

### ISSUE THREAD

**Issue by vojmar** [nanoframework/Home#480]
## Details about Problem
After clicking nanoFramework device in toolbar menu i get
https://cdn.discordapp.com/attachments/481780902058393610/582272079420719178/unknown.png
and
https://cdn.discordapp.com/attachments/481780902058393610/582272140040994874/unknown.png
**nanoFramework area:** 
Visual Studio extension

**VS version:**
15.9.12
**VS extension version:**
1.0.3.137, 1.0.3.140, 1.0.3.134 (all tested)

**VS output log:**
`1>------ Build started: Project: NFApp1, Configuration: Debug Any CPU ------
1>NFApp1 -> C:\Users\vojmar\source\repos\NFApp1\NFApp1\bin\Debug\NFApp1.exe
2>------ Deploy started: Project: NFApp1, Configuration: Debug Any CPU ------
2>There is no device selected. Please select a device in Device Explorer tool window.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========`
## Description
same/similar symptoms as:
https://github.com/nanoframework/Home/issues/457
no fix in that thread worked for me
## Detailed repro steps so we can see the same problem

![image](https://user-images.githubusercontent.com/18243945/58386453-566f4980-8000-11e9-9283-d8875bf812f7.png)
![image](https://user-images.githubusercontent.com/18243945/58386457-6555fc00-8000-11e9-8cda-9d7407dbf86a.png)
![image](https://user-images.githubusercontent.com/18243945/58386464-6e46cd80-8000-11e9-8e80-8e03c030f6c3.png)

## Additional context
I am using windos 10 - x64 and i used EspFirmwareFlasher (without any error message) to flash my device

**Comment by josesimoes** [comment]
In order to deploy a solution a nanoFramework device has to be selected in the Device Explorer window.

After 1st install of the nanoFramework extension, the developer has to go to View -> Other Windows and click on Device Explorer in order to make the window visible.
