### ISSUE TITLE
Documention has a dead link

### ISSUE THREAD

**Issue by toml2** [nanoframework/Home#493]
Readme.txt that opens after nuget update has a dead link:

API docs: https://docs.nanoframework.net/api/Windows.Devices.Wifi.html

**Comment by josesimoes** [comment]
Turns out that GitHub is picky with the casing. It should be WiFi.html... (note the capital F)

**Comment by kurtnelle** [comment]
Will do.

**Comment by kurtnelle** [comment]
Project Updated.
