### ISSUE TITLE
Output from DateTime.UtcNow seems to be wrong in ESP32

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#494]
## Details about Problem

**Target:** ESP32

**Firmware image version:** 1.0.4.500

Worked before? If so, with which nanoFramework image version:

## Description

The output from DateTime.UtcNow seems to be off.

## Detailed repro steps so we can see the same problem

1. Run this simple code block:
```
            Console.WriteLine($"{DateTime.UtcNow.ToString()}");
            Console.WriteLine($"{DateTime.UtcNow.ToString()}");
            Console.WriteLine($"{DateTime.UtcNow.ToString()}");
            Console.WriteLine($"{DateTime.UtcNow.ToString()}");
``` 

2. The output is:
![image](https://user-images.githubusercontent.com/1881520/60008261-b262d780-966b-11e9-9ade-a9fbcbf3a068.png)

## Expected behaviour

This is the output from the same code running on an STM32F769I-DISCO:
![image](https://user-images.githubusercontent.com/1881520/60008321-c8709800-966b-11e9-9a98-7e9791aae520.png)

**Comment by AdrianSoundy** [comment]
Issue is caused by latest millisec change.
