### ISSUE TITLE
Update URL for documentation on NuGet readme

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#495]
The documentation website has changed its organization. The docs home is now:
https://docs.nanoframework.net/content/intro.html

Need to update the readme for the NuGet packages on all class lib repos.

**Comment by kurtnelle** [comment]
Grabs

**Comment by josesimoes** [comment]
@kurtnelle suggest that you edit the file right on GitHub, then create a branch when asked.
It's the easier way to handle these small changes without having to go all the trouble of creating local repos, branches and submit PRs. And still meeting all the ceremony that this requires. 😉 

Of course this is just a suggestion. Feel free to handle it any way that works for you!

**Comment by kurtnelle** [comment]
Ok, I was confused for a bit there. There is not intro.html page under content. So the URL is just: https://docs.nanoframework.net/content/

Is that ok?

**Comment by josesimoes** [comment]
You are correct.
Actually https://docs.nanoframework.net just works.

**Comment by kurtnelle** [comment]
All projects updated.

**Comment by josesimoes** [comment]
Readme updated on all class lib repos. Closing.
