### ISSUE TITLE
Object.ReferenceEquals bug

### ISSUE THREAD

**Issue by MateuszKlatecki** [nanoframework/Home#496]
## Details about Problem

**nanoFramework area:** mscorelib

**VS version:**

**VS extension version:**

**Target:**

**Firmware image version:**

**Device capabilities output:**

## Description
```cs
var str = "Hello World!";
var s1 = "Hello ";
var s2 = "World!";

var str2 = s1 + s2;

var refEq = Object.ReferenceEquals(str, str2);
var objEq = Object.Equals(str, str2);

Console.WriteLine("Object.ReferenceEquals=" + refEq);
Console.WriteLine("Object.Equals=" + objEq);
```

Code above on nF returns:
```
Object.ReferenceEquals=True
Object.Equals=True
```
but on PC
```
Object.ReferenceEquals=False
Object.Equals=True
```

According to documentation https://docs.microsoft.com/en-US/dotnet/api/system.object.referenceequals?view=netframework-4.8 ReferenceEquals should only check if specified Object instances are the same instance, but in nF returns True if objects are equals.

**Comment by josesimoes** [comment]
The `ReferenceEquals` for strings (as explained on the link you've provided above) works slightly different from other object types. The method returns `true` if the string is interned. It does not perform a test for value equality. nanoFramework always interns strings therefore the call to `ReferenceEquals` for strings will always return `true`.
