### ISSUE TITLE
spi.write on ESP32 writes erronous data to the bus

### ISSUE THREAD

**Issue by kurtnelle** [nanoframework/Home#497]
public static void Main()
	{
		
		var spi = SpiDevice.FromId("SPI1", new SpiConnectionSettings(22));

		while (true)
		{
			spi.Write(new byte[] { 0x0 });
			Thread.Sleep(1000);
		}
	}

When I run this code on an ESP32, and monitor the output on my scope, I see a wall of data being sent (whereas the pin should just stay low). If I try and set the spi speed in the Connection Settings, the function spi.Write never returns, and just keeps toggling that output pin. The only way to get the device to respond after that is to erase the program and reset.

**Comment by josesimoes** [comment]
Can you please post a screenshot of the scope output?

Looking at the above code a continuous ouptut of 0x00 on the SPI bus is expected.

When you change the SPI bus speed to an erroneous value that can screw it. You don't mention to what value you're setting it... 

On the device becoming irresponsible that can happen too. The app is continously writing to the bus with 1sec interval to breath. It could be hard for the debugger comms to pick-up the incoming requests...

PS: please respect the issues template next time. 🙂

**Comment by kurtnelle** [comment]
![DS1Z_QuickPrint1](https://user-images.githubusercontent.com/6971127/60411819-9647c480-9b9c-11e9-831b-b09fac256070.png)
This is a trace of the start of the data

![DS1Z_QuickPrint3](https://user-images.githubusercontent.com/6971127/60411832-a2cc1d00-9b9c-11e9-81c9-55f768cf3f6c.png)
This seemingly random pattern goes on for a while. The slower I set the clock frequency, the longer the pattern runs for. I had to change the frequency because I was getting a distorted signal on the scope.

````   
public class Program
    {
        public static void Main()
        {
            
            var spi = SpiDevice.FromId("SPI1", new SpiConnectionSettings(22) { ClockFrequency = 1 * 1000 * 1000 });

            while (true)
            {
                spi.Write(new byte[] { 0x0 });
                Thread.Sleep(10000);
            }
        }
    }
````

**Comment by kurtnelle** [comment]
Sorry, context. Purple is CS yellow is MOSI and blue is CLK

**Comment by josesimoes** [comment]
Agreed: that doesn't feel right.

**Comment by AdrianSoundy** [comment]
The problem is caused by not settings the DataBitLength property in the SpiConnectionSettings

var spi = SpiDevice.FromId("SPI1", new SpiConnectionSettings(22) { ClockFrequency = 1 * 1000 * 1000,  DataBitLength = 8  });

I'll add a change to make sure it defaults to 8 if not specified instead of 0

**Comment by kurtnelle** [comment]
The proposed solution works!

![DS1Z_QuickPrint1](https://user-images.githubusercontent.com/6971127/60474270-fabb6000-9c3e-11e9-90e6-2cf90382beeb.png)
