### ISSUE TITLE
Deployment progress message shows wrong counters

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#500]
## Details about Problem

**nanoFramework area:** Visual Studio extension

**VS version:**

**VS extension version:**

**Target:**

**Firmware image version:**

**Device capabilities output:**

## Description

When the error messages are enabled, a progress message during deployment is output. The message content shows always the same numbers.

## Detailed repro steps so we can see the same problem

1. Deploy any solution to any target

2. Output from VS window:

![image](https://user-images.githubusercontent.com/1881520/60956139-19ce8780-a2fa-11e9-9f0e-6dfe0de4d48d.png)

## Expected behaviour

The counters should be updating as the deployment progresses.

**Comment by networkfusion** [comment]
issue is with `source/nanoFramework.Tools.DebugLibrary.Shared/WireProtocol/Engine.cs` line `2835` in that the progress is only showing the current block size being deployed against the total amount of blocks.
it requires a var to increment the amount of bytes deployed.
