### ISSUE TITLE
Revert MinSizeRel LTO options for NXP port

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#506]
LTO optimizations on MinSizeRel had to be disabled after updating the Azure Pipeline to GCC 8 2019 Q3 update [here](nanoframework/nf-interpreter#1411).

Required fixes to FreeRTOS [proposed](https://github.com/aws/amazon-freertos/pull/968). 

After the above PR is merged, LTO optimizations can be enabled again.

cc @MateuszKlatecki

**Comment by networkfusion** [comment]
Merged here: https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/71

**Comment by josesimoes** [comment]
still active
