### ISSUE TITLE
Review ESP32 partition tables

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#507]
The partition tables for ESP32 need to be reviewed for consistency.

- [ ] config block as different sizes on 2M, 4M and 16M
- [ ] deploy area has the same size on 4, 8 and 16M (shouldn't it be extended to take advantage of the available space?)

cc @nanoframework/esp32-developers

**Comment by AdrianSoundy** [comment]
I left the partition sizes as there were for now for a number of reasons.
Most devices are at least 4MB.
- 1MB nanoCLR is big enough
- 1.7 MB deployment area is probably enough for most people.
- Config area is the Spiffs file system and can be used for general use. This could be increased
- Until we have some idea of how OTA updates will work there was no point configuring for it.

For OTA we would need 2 partitions for nanoCLR and Deployment
- Probably would want to do an OTA update with both areas in one download or maybe just deployment.
