### ISSUE TITLE
'lib-nanoFramework.System.Net.Http' prevents Apps from running in debug mode

### ISSUE THREAD

**Issue by RoSchmi** [nanoframework/Home#515]
nanoFramework area: lib-nanoFramework.System.Net.Http
VS version: VS 2017 Version 15.9.14
VS extension version: 1.2.0.3
Target: NUCLEO STM23F746
Firmware image version:1.1.161.0

I create a new project in Visual Studio with binaries from the dev-branch (see picture). When I add the nuget package 'nanoFramework.System.Net' and deploy the project everything works fine. When I then add the nuget package 'nanoFramework.System.Net.Http' and deploy the project the application doesn't start (see pictures with messages in the output window.

![httpcrash_libraries](https://user-images.githubusercontent.com/24595510/63158394-6f910080-c019-11e9-88b0-5ca464d109dd.png)

![htpcrash_mess_1](https://user-images.githubusercontent.com/24595510/63158413-7c155900-c019-11e9-9ae4-06bdbd4644b1.png)

![httpcrash_Mess_2](https://user-images.githubusercontent.com/24595510/63158422-833c6700-c019-11e9-863b-d524b46366cf.png)

**Comment by josesimoes** [comment]
It seems that you're referencing nanoFramework.System.Net.Http version 1.0.6-preview.30 when the latest one is 1.0.6-preview.33.

As mentioned abundantly elsewhere if you are using develop stuff, make sure you add our MyGet feed to your NuGet configuration.

**Comment by RoSchmi** [comment]
Thanks, I can confirm. With ..Net.Http version 1.0.06-preview.33 it works. Shall I close the issue?

**Comment by josesimoes** [comment]
Awesome! Yes please

**Comment by RoSchmi** [comment]
Closed.
