### ISSUE TITLE
Add support for the ESP32 Remote Control (RMT) peripheral

### ISSUE THREAD

**Issue by marknotgeorge** [nanoframework/Home#518]
The ESP32 chip has a Remote Control (RMT) peripheral, which facilitates transmitting and receiving infra-red remote control signals. Further details can be found in the [IDF documentation](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/rmt.html).

It would also be useful to add support for IR code formats and protocols. Support for code databases such as [irdb](http://irdb.tk/) might be an idea.

**Comment by josesimoes** [comment]
Nice that you are looking into this! 👏 

Being a "niche" feature the use scenarios are very specific. Meaning that the inclusion of the native code should be dependent of a build feature. For the same reason the supporting API should be a class library on its own.

**Comment by marknotgeorge** [comment]
@ololoshka2871 has already been [working on this](https://github.com/ololoshka2871/nanoFramework.Hardware.Esp32.RMT)

**Comment by josesimoes** [comment]
Still active, correct @marknotgeorge 😁?
