### ISSUE TITLE
Windows.Storage not implemented in Quail firmware

### ISSUE THREAD

**Issue by blobbynf** [nanoframework/Home#521]
2>Deploy failed.
2>**
2>Couldn't find a valid native assembly required by Windows.Storage v1.0.1.0, checksum 0x8D8C8026.
2>This project is referencing Windows.Storage NuGet package requiring native v100.0.1.0.
2>The connected target does not have support for Windows.Storage.
2>Please check: 
2>  1) if the target is running the most updated image.
2>  2) if the target image was built to include support for all referenced assemblies.
2>**

When I look at the device capabilities, I get this :
Native Assemblies:
  mscorlib v100.2.2.0, checksum 0x6AC9143D
  nanoFramework.Runtime.Native v100.0.5.0, checksum 0x153CD2E3
  nanoFramework.Hardware.Stm32 v100.0.4.3, checksum 0x3E87EA8A
  nanoFramework.Devices.OneWire v100.0.3.3, checksum 0xC7BEAEBC
  nanoFramework.Runtime.Events v100.0.6.0, checksum 0x9E949BB1
  EventSink v1.0.0.0, checksum 0xF32F4C3E
  System.Math v100.0.4.3, checksum 0xC5A2A195
  Windows.Devices.Gpio v100.1.1.0, checksum 0xD7F65BB7
  Windows.Devices.I2c v100.2.0.0, checksum 0x100B5D05
  Windows.Devices.Pwm v100.1.3.1, checksum 0x8E93FB40
  Windows.Devices.SerialCommunication v100.1.0.0, checksum 0x4B336BE9
  Windows.Devices.Spi v100.1.3.0, checksum 0xBDDC51FB

I am using  firmware "MBN_QUAIL-1.0.5-preview.4" and the nugets from  https://pkgs.dev.azure.com/nanoframework/feed/_packaging/sandbox/nuget/v3/index.json

**Comment by networkfusion** [comment]
@blobbynf if you are able to test the PR and correct the SD line detection pin (if necessary) that would be a great help...
