### ISSUE TITLE
STM32F769I-DISCO not showing up in VS2017 Device Explorer

### ISSUE THREAD

**Issue by tpitman** [nanoframework/Home#522]
## Details about Problem

**Target:**
STM32F769I-DISCO

**Firmware image version:**
nfbot / nanoframework-images-dev / ST_NUCLEO144_F746ZG / 1.0.2-preview.195

Worked before? If so, with which nanoFramework image version:
No

## Description

I am following the getting started. I have the above board. I use STLink Util to flash. After flashing bootloader the led blinks fast red/green for a second then pauses on green. Since this is a different board than the getting started I am not sure if that is considered a slow blink. I continue and flash the CLR. After that the led just stays green.

The device never shows up in Visual Studio 2017 Extension.

**Comment by josesimoes** [comment]
Hi @tpitman. Welcome to nanoFramework.


From your description you are referring to the LED that flashed on ST Link activity not LD2 that slow blinks green when nanoBooter is running.

Also not clear on what image you are loading on your device. If it's a STM32F769I-DISCO you have to load the image for that one. If you flash it with the one from the 769, it wont boot.

The getting started for STM32 needs an update...

Suggest that you use [nanoff](https://github.com/nanoframework/nanoFirmwareFlasher) instead. Just follow the instruction on the repo.
And make sure you unplug and plug the USB cable of the DISCO board.

Final suggestion: join our Discord char [here]( https://discord.gg/gCyBu8T) as suggested in the issue template for better support on question like this one. 😉

**Comment by josesimoes** [comment]
🤔  that's a bug.... where is that link please, so it can be fixed?

**Comment by networkfusion** [comment]
![image](https://user-images.githubusercontent.com/11439699/63718338-3ee36f00-c842-11e9-8b26-e31f27ef4cd2.png)

**Comment by networkfusion** [comment]
Thanks, I have now corrected the document.
Our discord community is very active if you need any help...
