### ISSUE TITLE
Opening Device Explorer Crashes Windows

### ISSUE THREAD

**Issue by RobLawlor2** [nanoframework/Home#535]
Hello,
I have just attempted to use the nano Framework , however I get a system crash(blue screen) when I attempt to open device explorer.
I can open templates for the nano framework and build them.

I get this system crash with both VS2019 and VS2017.

Microsoft Visual Studio Professional 2019 (2)
Version 16.3.5
VisualStudio.16.Release/16.3.5+29411.108
Microsoft .NET Framework
Version 4.8.03761

nanoFrameWork  version 1.2.5.8

**Comment by josesimoes** [comment]
What is the target device you are using?

**Comment by RobLawlor2** [comment]
I have no target device as of yet. A STM32 Nucleo-144  (STM32F746ZGT6)  should be arriving tomorrow.
However the issue is not with attmpting to connect, rather the device explorer window does not open and windows crashes.

**Comment by josesimoes** [comment]
🤔 the only explanation that occurs to me is that one of the COM ports connected is misbehaving... 
We had reports before on failed auto-detection with BLE virtual COM ports. But nothing like that.

The only BSoD report was related with outdated versions of FTDI drivers and ESP32 target boards.h
Any of the above helps?

**Comment by RobLawlor2** [comment]
Hi ,
I had some virtual Com ports setup using com0com.
I uninstalled them and the device explorer opened without crashing.
Thank you very much. I'm looking forward to using the nano framework now.

**Comment by josesimoes** [comment]
Nice!

Glad that you've managed to get past this.
Wish you a lot of fun with nanoFramework.

Make sure you join our friendly [Discord community](https://discord.gg/gCyBu8T). 😉

**Comment by josesimoes** [comment]
If you could provide the VID/PID or other USB ID that can be used to identify those virtual COM ports that would allow us to add those to the exclusion list so they are skipped during the detection.

**Comment by RobLawlor2** [comment]
Hi, the IDs are as follows:

root\com0com
com0com\port
com0com\comport

thanks again.
