### ISSUE TITLE
HTTP WebRequest throws SocketException

### ISSUE THREAD

**Issue by JeremyKnaggs** [nanoframework/Home#542]
## Details about Problem

**Target:** ESP32

**Firmware image version:** 1.4.0-Preview.34

Worked before? If so, with which nanoFramework image version:
 Yes, currently works with stable FW 1.3.2

## Description

HTTP (non ssl) web requests result in exception: exception of type 'System.Net.WebException' occurred in System.Net.Http.dll

## Detailed repro steps so we can see the same problem

1. Using ESP32 and firmware 1.4.0-Preview.34. 

2. Run below method to request text at URL http://knaggsfam.com/hi.txt: 

            public static void Main()
            {
            var networkHerlpers = new NetworkHelpers();
            NetworkHelpers.SetupAndConnectNetwork(true);

            Console.WriteLine("Waiting for network up and IP address...");

            NetworkHelpers.IpAddressAvailable.WaitOne();

            Console.WriteLine("Waiting for valid Date & Time...");

            NetworkHelpers.DateTimeAvailable.WaitOne();
            string url = "http://knaggsfam.com/hi.txt";

            Console.WriteLine($"Performing Http request to: {url}");

            using (var httpWebRequest = (HttpWebRequest)WebRequest.Create(url))
            {
                httpWebRequest.Method = "GET";
                using (var stream = httpWebRequest.GetResponse().GetResponseStream())
                {
                    // read response in chunks of 1k

                    byte[] buffer = new byte[1024];
                    int bytesRead = 0;

                    Console.WriteLine("Http response follows");
                    Console.WriteLine(">>>>>>>>>>>>>");

                    do
                    {
                        bytesRead = stream.Read(buffer, 0, buffer.Length);
                        Console.Write(Encoding.UTF8.GetString(buffer, 0, bytesRead));
                    }
                    while (bytesRead >= buffer.Length);
                }

                Console.WriteLine(">>>>>>>>>>>>>");
                Console.WriteLine("End of Http response");
            }
        }

3. Above method results in output:
The thread '<No Name>' (0x3) has exited with code 0 (0x0).
Performing Http request to: http://knaggsfam.com/hi.txt
    #### Exception System.Net.Sockets.SocketException - CLR_E_FAIL (1) ####
    #### Message: 
    #### System.Net.Sockets.NativeSocket::ioctl [IP: 0000] ####
    #### System.Net.Sockets.Socket::get_Available [IP: 0018] ####
    #### System.Net.Sockets.NetworkStream::get_Length [IP: 001f] ####
    #### System.Net.InputNetworkStreamWrapper::Read_HTTP_Line [IP: 004b] ####
    #### System.Net.HttpWebRequest::ParseHTTPResponse [IP: 002e] ####
    #### System.Net.HttpWebRequest::GetResponse [IP: 0035] ####
    #### SecureClient.Program::Main [IP: 004a] ####
    #### Exception System.Net.WebException - 0x00000000 (1) ####
    #### Message: 
    #### System.Net.HttpWebRequest::GetResponse [IP: 00c8] ####
    #### SecureClient.Program::Main [IP: 004a] ####
Exception thrown: 'System.Net.WebException' in System.Net.Http.dll
An unhandled exception of type 'System.Net.WebException' occurred in System.Net.Http.dll
...

## Expected behaviour
Current Stable build 1.3.2 results in the expected output (txt file at URL contains 'hi'):

Performing Http request to: http://knaggsfam.com/hi.txt
Http response follows
>>>>>>>>>>>>>
hi>>>>>>>>>>>>>
End of Http response

**Comment by josesimoes** [comment]
It's working now. I believe that's because of the several improvements that were introduced with nanoframework/lib-nanoFramework.System.Net.Http#63.
