### ISSUE TITLE
Type Resolution Failure while initiating Debug Session

### ISSUE THREAD

**Issue by JeremyKnaggs** [nanoframework/Home#544]
## Details about Problem
Projects are no longer successfully pushed to ESP32. The build/push is interrupted with an error.
**Target:**
ESP32
**Firmware image version:**
Preview 1.4.0-preview-.55
Worked before? If so, with which nanoFramework image version: Yes, this worked with the latest stable 1.3.2

## Description
After starting a "Debug" session, Visual Studio appears to attempt a build then push to the ESP32. However, the process is interrupted by the following error:
Attaching to nanoDevice...
Waiting for nanoDevice to initialize...
******************************************************************************
The program '[1] nanoFramework application: Managed' has exited with code 0 (0x0).
** Error: Device stopped after type resolution failure.                     **
** Check in each assembly which assemblies are referenced and their version **
******************************************************************************
The nanoDevice target and the debugger engine failed to initialize because of unspecified device errors.
The debugger engine thread has terminated unexpectedly with error 'Device stopped after type resolution failure. Can't start execution.'.

## Detailed repro steps so we can see the same problem
I've attached a simple project which will not successfully load to the ESP32.
[WxStation.zip](https://github.com/nanoframework/Home/files/3856156/WxStation.zip)

1. Open project in Visual Studio

2. Start Debug session. The error will appear in the Visual Studio Output window

## Expected behaviour
The expected

 behavior is for the Debug session to start successfully.

## Additional context
The Assemblies which are loaded include:

Assemblies:
  WxStation, 1.0.0.0
  nanoFramework.Runtime.Native, 1.2.0.0
  System.Net.Http, 1.2.2.0
  nanoFramework.System.Text, 1.0.0.0
  mscorlib, 1.6.0.0
  System.Net, 1.4.1.0
  nanoFramework.Hardware.Esp32, 1.2.0.0
  nanoFramework.ResourceManager, 1.0.0.0
  nanoFramework.Runtime.Events, 1.4.1.0
  nanoFramework.System.Collections, 1.0.0.0
  Windows.Devices.Wifi, 1.2.0.0

Native Assemblies:
  mscorlib v100.4.6.0, checksum 0x3E5F09B0
  nanoFramework.Runtime.Native v100.0.6.0, checksum 0x035EC7E8
  nanoFramework.Hardware.Esp32 v100.0.7.0, checksum 0xC16385A2
  nanoFramework.Devices.OneWire v100.0.3.3, checksum 0xC7BEAEBC
  nanoFramework.Networking.Sntp v100.0.4.3, checksum 0xB617FDFB
  nanoFramework.ResourceManager v100.0.0.0, checksum 0xCDF9E76C
  nanoFramework.System.Collections v100.0.0.0, checksum 0xC7167094
  nanoFramework.System.Text v100.0.0.0, checksum 0x482137FC
  nanoFramework.Runtime.Events v100.0.7.0, checksum 0x7B4AC2F2
  EventSink v1.0.0.0, checksum 0xF32F4C3E
  System.Math v100.0.4.3, checksum 0xC5A2A195
  System.Net v100.1.3.0, checksum 0x0B718489
  Windows.Devices.Adc v100.1.3.2, checksum 0xDEDF1136
  Windows.Devices.Gpio v100.1.2.0, checksum 0x2432E7EB
  Windows.Devices.I2c v100.2.0.1, checksum 0x8D1C8F95
  Windows.Devices.Pwm v100.1.3.2, checksum 0x84D8B10C
  Windows.Devices.SerialCommunication v100.1.1.0, checksum 0x8E46E2E2
  Windows.Devices.Spi v100.1.4.0, checksum 0xEA555AF2
  Windows.Devices.Wifi v100.0.6.0, checksum 0x5AC050C9
  Windows.Storage v100.0.1.0, checksum 0x8D8C8026

**Comment by josesimoes** [comment]
Turns out that the latest nanoFramework.Hardware.Esp32 release got stuck on the approval queue and was never released.
Please update it to https://github.com/nanoframework/lib-nanoFramework.Hardware.Esp32/releases/tag/v1.2.0-preview.8 and the type resolution failure will be gone.

⚠️  make sure there is no app.config generated after the NuGet update ⚠️
