### ISSUE TITLE
Netduino Plus support

### ISSUE THREAD

**Issue by Matthias1172** [nanoframework/Home#546]
Hello.
I have an old Netduino Plus which I wanted to program via nanoFramework.
i couldn't find any firmware for this board. Is it actually supported or is there any way to make it running nF?
Thanks in advance for your support.

**Comment by josesimoes** [comment]
Hi,

We don't have a "ready to flash" image for this board.

Adding this as feature request in case someone is willing to add the target to the community targets.

**Comment by piwi1263** [comment]
@Matthias1172  What Netduino Plus are you refering to, V1 or v2?

**Comment by networkfusion** [comment]
@Matthias1172 given there has been no response, I am going to close the issue, however, if it is still a problem feel free to reopen it. Better yet, please discuss in our discord community first.
