### ISSUE TITLE
How can i run DFPlayer with nanoframework?

### ISSUE THREAD

**Issue by DenisMtfl** [nanoframework/Home#550]
Is it possible?

**Comment by josesimoes** [comment]
Please enlighten us on what is DFPLayer...

**Comment by DenisMtfl** [comment]
The DFPlayer Mini MP3 Player For Arduino is a small and low price MP3 module with an simplified output directly to the speaker. The module can be used as a stand alone module with attached battery, speaker and push buttons or used in combination with an Arduino UNO or any other with RX/TX capabilities.

Source:
https://wiki.dfrobot.com/DFPlayer_Mini_SKU_DFR0299

**Comment by DenisMtfl** [comment]
> Please enlighten us on what is DFPLayer...

@josesimoes 
The DFPlayer Mini MP3 Player For Arduino is a small and low price MP3 module with an simplified output directly to the speaker. The module can be used as a stand alone module with attached battery, speaker and push buttons or used in combination with an Arduino UNO or any other with RX/TX capabilities.

Source:
https://wiki.dfrobot.com/DFPlayer_Mini_SKU_DFR0299

**Comment by josesimoes** [comment]
Being controlled over a serial port you're good to go with nanoFramework.
Please check the SerialCommunication pack in the samples repo. You'll find there all you need to get you started.

**Comment by DenisMtfl** [comment]
Thanks! I will try.

**Comment by VitalyV** [comment]
Hi @DenisMtfl.
Did you manage to send a command or read the data from DFPlayer?
Thanks

**Comment by kamszyc** [comment]
It can be controlled using Yx5300 class, described here
https://docs.nanoframework.net/devicesdetails/Yx5300/README.html

This issue comes up first on Google search, so I thought this info can help someone
