### ISSUE TITLE
DFU packages only reach nanoBooter if memory not fully cleared

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#555]
## Details about Problem

**nanoFramework area:** 
nanoFirmwareFlasher 
ST DFU Demo

**Target*
OrgPalThree (and maybe others)

**Firmware image version:**
Latest (as of 2019-01-17)

## Description

When flashing a DFU package to a board that already contains the booter and CLR, once updated successfully, the board only boots into nanoBooter, and seems incapable of reaching the CLR

## Workaround
Use the ST DFU testing app to fully erase the memory - Side effect is that all config region is lost.

## Possible fixes
Only create a DFU file that contains the CLR
Move Config Region to end of memory
...

**Comment by networkfusion** [comment]
Further ideas / resources at:
https://github.com/networkfusion/St-Dfu
https://github.com/pimoroni/DfuSE/

**Comment by networkfusion** [comment]
@piwi1263 does the erase work as expected with the latest nanoff release?

**Comment by networkfusion** [comment]
Still seems to be an issue with the orgpal3 after the recent improvements to nanoff.

**Comment by networkfusion** [comment]
Tested as of 2020-05-24 with latest image and nanoff, but is still an issue.

**Comment by josesimoes** [comment]
@networkfusion what is the version of nanoff that you're using?
I've just run this with the latest (v1.12.1) and also on VS in debug and the update is performed as expected. I've checked the config block and the contents remain untouched during the udpate.
