### ISSUE TITLE
Adding new Resource file 

### ISSUE THREAD

**Issue by valoni** [nanoframework/Home#559]
Please read the following information before posting the issue.

## Details about Problem

when you try to add an resource file on Visual Studio 2019 it stuck forever on loop 

Visual Studio 2019 v16.4.3 vsix extension 1.3.0.1 

## Description

Do not create resource file and add to the project ...

## Detailed repro steps so we can see the same problem

step to reproduce that 

![image](https://user-images.githubusercontent.com/238540/73446878-e585eb80-435d-11ea-830e-6b6a358a087b.png)

![image](https://user-images.githubusercontent.com/238540/73446890-ef0f5380-435d-11ea-942b-ad5a193a6319.png)

**Comment by josesimoes** [comment]
Could this be a regression of #470? Or maybe they have "fixed" something in the standard targets files that is now colliding with the previous fix...

**Comment by josesimoes** [comment]
Does this happen in VS2017 too?

**Comment by valoni** [comment]
> Does this happen in VS2017 too?

on Visual Studio 2017 work well - no problem or any issues with Resources seem only on Visual Studio 2019 cause a break.

**Comment by josesimoes** [comment]
Oh... here we go again… 🤕

**Comment by josesimoes** [comment]
Reported to VS Developer Community. See [here](https://developercommunity.visualstudio.com/content/problem/956161/resource-file-with-visual-studio-2019-v165.html?childToView=956382#comment-956382)

## Please upvote the issue above so it get's higher on the priority list

**Comment by mariodivece** [comment]
Same issue here with VS 2019 :(

**Comment by josesimoes** [comment]
@mariodivece yes the issue remains unsolved. It's stuck on Microsoft queue.
It will get attention when enough people up vote.
Please go to the VS developer community site link above and up vote there.

**Comment by meanshe** [comment]
Same issue here with VS 2019 :(

**Comment by josesimoes** [comment]
@meanshe the issue remains to be solved by Microsoft. Please up vote on the link above.

**Comment by josesimoes** [comment]
Issue fixed. Schedule to release with VS 16.8.

**Comment by valoni** [comment]
on wait from MS to resolve problem ..

**Comment by valoni** [comment]
Resolved with latest update of Visual Studio 16.8.0

**Comment by antonsterkhov** [comment]
Same issue here with VS 2022 :(
