### ISSUE TITLE
SpiDevice.FromId hangs on ESP32

### ISSUE THREAD

**Issue by huysentruitw** [nanoframework/Home#563]
## Details about Problem

**nanoFramework area:** C# code

**VS version:** 2019

**VS extension version:** 1.3.0.1

**Target:** ESP32

**Firmware image version:** 1.4.0-preview.93

## Description

Calling `SpiDevice.FromId` makes the board hang, when stepping while debugging, I'm not getting over this call.

```csharp
_device = SpiDevice.FromId("SPI1", new SpiConnectionSettings(8)
{
    BitOrder = DataBitOrder.MSB,
    ClockFrequency = 1000000,
    Mode = SpiMode.Mode0,
    SharingMode = SpiSharingMode.Shared,
    DataBitLength = 8,
});
```

## Expected behaviour

Shouldn't hang.

## Additional context

A call to `SpiDevice.GetDeviceSelector()` returns `SPI1,SPI2`.

**Comment by josesimoes** [comment]
This happens because you're using pin 8 for CS. Try another one, e.g. 22 and it will work.
