### ISSUE TITLE
Unable to deploy if using enum or thread

### ISSUE THREAD

**Issue by TheTrigger** [nanoframework/Home#569]
## Details about Problem

**nanoFramework area:** Deploy and debugging

**VS version:** vs17 & vs19

**VS extension version:** 1.4.0.6

**Target:** ESP32

**Nuget CoreLibrary:** 1.6.0-preview.1

**Firmware image version:** 1.4.0-preview.110

**Device capabilities output:**
```
Attaching to nanoDevice...
Waiting for nanoDevice to initialize...
Updating nanoDevice debugger engine.
The nanoDevice runtime is loading the application assemblies and starting execution.
The program '[1] nanoFramework application: Managed' has exited with code 0 (0x0).
```

## Description

Debug ends if use Enum as parameter. The code is not even executed (or deployed? idk)

## Detailed repro steps so we can see the same problem

- create app
- link library
- - add a class that has a method with enum as signature
- - create a `new Thread`
- deploy
+ see attached project

## Expected behavior

Able to deploy and debug, or see any error

### Sample Project

[NFApp3.zip](https://github.com/nanoframework/Home/files/4221827/NFApp3.zip)

**Comment by josesimoes** [comment]
Can't reproduce the 1st reported bug with launching a thread. See below:
![image](https://user-images.githubusercontent.com/1881520/74836704-d6200f80-5317-11ea-830b-5607f9b03fee.png)
