### ISSUE TITLE
VSIX do not detect STM32 boards

### ISSUE THREAD

**Issue by valoni** [nanoframework/Home#572]
After update-in VSIX 1.7.0.6 and installed firmware for NUCLEO F411 version 1.1.328 .0
when tried to detect boards showing 

VSIX do not detect boards (STM32F4..)

message : 
**2020-02-25 22:03:50Z [NanoDevices: checking device  \\?\USB#VID_0483&PID_374B&MI_02#6&3381915F&1&0002#{86e0d1e0-8089-11d0-9ce4-08003e301f73} with invalid DeviceBase]**

it also confirmed with official board too Netduino3_Wifi firmware 1.4.0.preview.115

![image](https://user-images.githubusercontent.com/238540/75287660-0c2f2900-581b-11ea-97fb-7bf6ef95e72f.png)

**Comment by josesimoes** [comment]
After several tests I've come to the following conclusion: this seems to happen with STM boards that use the STLink USB connection **and** the firmware that includes Mass Storage.

If you install the firmware **without** Mass Storage option the board detection works as expected.

![image](https://user-images.githubusercontent.com/1881520/75342272-fd358e80-588d-11ea-84cf-6d9204031c45.png)
✔️  Funcional



![image](https://user-images.githubusercontent.com/1881520/75342481-6fa66e80-588e-11ea-8da3-54493c1ef044.png)

🔴 NOT funcional

Further investigation is required...

**Comment by josesimoes** [comment]
Recommendation to update firmware on boards with STM32 STLink to v2.36.26.

https://www.st.com/content/st_com/en/products/development-tools/software-development-tools/stm32-software-development-tools/stm32-programmers/stsw-link007.html

**Comment by josesimoes** [comment]
NETDUINO3_WIFI is not enumerating USB device properly. It's an issue, of course, but should be unrelated.

**Comment by josesimoes** [comment]
Should be fixed with VS extension v1.7.0.9.
