### ISSUE TITLE
Extension 1.7.0.10 and newer didn't detect target

### ISSUE THREAD

**Issue by MateuszKlatecki** [nanoframework/Home#576]
## Details about Problem

**nanoFramework area:** Visual Studio extension 

**VS version:** 2017

**VS extension version:** >= 1.7.0.10

**Target:**

**Firmware image version:**

**Device capabilities output:**

## Description

Since 1.7.0.10 version  target detection is not working

**Comment by josesimoes** [comment]
Which target?

**Comment by MateuszKlatecki** [comment]
Our custom board (based on NXP_MIMXRT1060_EVK ) With previous version of extension we didn't any problems.

**Comment by MateuszKlatecki** [comment]
In VS2019 extension find device
After merge this commit https://github.com/nanoframework/nf-interpreter/commit/68fc83c6f449b2d0f4d4bd8722c477fa57422864 VS2017 works too
