### ISSUE TITLE
Comparison with Float.NaN and Double.NaN

### ISSUE THREAD

**Issue by MateuszKlatecki** [nanoframework/Home#577]
## Details about Problem

**Target:** not relevant

**Firmware image version:** not relevant

## Description

when compare variable to Single.NaN or Double.NaN result is incorrect
```C#
            float n = 1.0F;

            if (n == Single.NaN)
            {
                Console.WriteLine("1==NaN");
            }
```

## Expected behaviour

Any comparison to NaN must be always false (even NaN == NaN)

## Additional context

Change need be done in interpreter.
See for example:  https://docs.microsoft.com/en-gb/dotnet/api/system.reflection.emit.opcodes.ceq?redirectedfrom=MSDN&view=netframework-4.8
```
For floating-point number, ceq will return 0 if the numbers are unordered (either or both are NaN). The infinite values are equal to themselves.
```

**Comment by networkfusion** [comment]
Just checking that you are running a firmware with "Double"support enabled, since no reference image does? If so, can you add the relevant details...
