### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by furesoft** [nanoframework/Home#583]
Can i Use NanoFramework on Raspberry pi?

**Comment by networkfusion** [comment]
Not currently,  although it is technically possible. Although since the raspberry pi can run the full .net core framework, I am not sure what you would achieve by doing so... This type of question would be better answered on our discord channel if further comment is required.

**Comment by asheesh1996** [comment]
Can I Use NanoFramework on Raspberry pi and configure wifi using System.Devices.Wifi package as well as any chance for BLE?

**Comment by Ellerbach** [comment]
> Can I Use NanoFramework on Raspberry pi and configure wifi using System.Devices.Wifi package as well as any chance for BLE?

No, you cannot use .NET nanoFramework on a Raspberry Pi. But you can use .NET IoT, see https://github.com/dotnet/iot/. API are aligned, so you can almost use the same code on both platforms.

**Comment by asheesh1996** [comment]
> No, you cannot use .NET nanoFramework on a Raspberry Pi. But you can use .NET IoT, see https://github.com/dotnet/iot/. API are aligned, so you can almost use the same code on both platforms.
As I mentioned in my question, I want to use [System.Devices.Wifi](https://www.nuget.org/packages/nanoFramework.System.Device.Wifi/) package and [BLE package](https://github.com/nanoframework/nanoFramework.Device.Bluetooth) on raspberry pi and there are not much libraries for these functionalities.

**Comment by josesimoes** [comment]
> > No, you cannot use .NET nanoFramework on a Raspberry Pi. But you can use .NET IoT, see https://github.com/dotnet/iot/. API are aligned, so you can almost use the same code on both platforms.
> 
> As I mentioned in my question, I want to use [System.Devices.Wifi](https://www.nuget.org/packages/nanoFramework.System.Device.Wifi/) package and [BLE package](https://github.com/nanoframework/nanoFramework.Device.Bluetooth) on raspberry pi and there are not much libraries for these functionalities.

These libraries are meant to be used in .NET nanoFramework projects. To my knowledge there are no equivalents for .NET that you can use in the RPII. 

Suggest that you ask on .NET IoT repo or their [Discord](https://discord.gg/YD58GfFS) server.
