### ISSUE TITLE
Gpio interrupts have stopped working for ESP32 (and STM32?)

### ISSUE THREAD

**Issue by skigrinder** [nanoframework/Home#586]
The following code was working a few weeks ago but it no longer triggers the event handler when the device is activated:

            using Windows.Devices.Gpio;
            using nanoFramework.Hardware.Esp32;

            private static GpioPin FC51_01;
          
            FC51_01 = gpioController.OpenPin(Gpio.IO19, GpioSharingMode.SharedReadOnly);
            FC51_01.DebounceTimeout = new TimeSpan(0, 0, 0, 0, 50);
            FC51_01.SetDriveMode(GpioPinDriveMode.InputPullDown);
            FC51_01.ValueChanged += FC51_01_gpioValueChanged;

           private static void FC51_01_gpioValueChanged(object sender,          GpioPinValueChangedEventArgs e) {
                   Console.WriteLine("FC51_01_gpioValueChanged()  hit : " + e.Edge.ToString());
           }

I've tested this for ESP32 with the latest nanoFramework VS extension & Nuget libraries.
Changes to the DebounceTimeout & GpioPinDriveMode did not resolve the issue.

**Comment by piwi1263** [comment]
Hi @josesimoes and @skigrinder I guess I have the same issue or at least similar. After updating the Quail (STM32) board support for the microSD Click board only the remove event is fired, the insert event never does.

**Comment by martin-kuhn** [comment]
Yes, my button interrupt does not work anymore either on STM32 with the latest version.

**Comment by josesimoes** [comment]
I've managed to reproduce the issue. Working on it. Please be patient.
