### ISSUE TITLE
Error deploy in ESP32

### ISSUE THREAD

**Issue by andceoynnova** [nanoframework/Home#593]
I try to compile and deploy blink example but it can't deploy in target ESP32.

System Information
HAL build info: nanoFramework running ESP32 built with IDF v3.1
  Target:   ESP32_WROOM_32
  Platform: ESP32

Firmware build Info:
  Date:     Oct 17 2019
  Type:     nanoFramework running ESP32 built with IDF v3.1
  Version:  1.3.2.3
  Compiler: GNU ARM GCC v5.2.0

OEM Product codes (vendor, model, SKU): 0, 0, 0

Serial Numbers (module, system):
  00000000000000000000000000000000
  0000000000000000

AppDomains:

Assemblies:

Native Assemblies:
  mscorlib v100.2.3.0, checksum 0x91CE6848
  nanoFramework.Runtime.Native v100.0.5.0, checksum 0x153CD2E3
  nanoFramework.Hardware.Esp32 v100.0.7.0, checksum 0xC16385A2
  nanoFramework.Devices.OneWire v100.0.3.3, checksum 0xC7BEAEBC
  nanoFramework.Networking.Sntp v100.0.4.3, checksum 0xB617FDFB
  nanoFramework.Runtime.Events v100.0.6.0, checksum 0x9E949BB1
  EventSink v1.0.0.0, checksum 0xF32F4C3E
  System.Math v100.0.4.3, checksum 0xC5A2A195
  System.Net v100.1.3.0, checksum 0x0B718489
  Windows.Devices.Adc v100.1.3.1, checksum 0xA84B23D2
  Windows.Devices.Gpio v100.1.1.0, checksum 0xD7F65BB7
  Windows.Devices.I2c v100.2.0.0, checksum 0x100B5D05
  Windows.Devices.Pwm v100.1.3.1, checksum 0x8E93FB40
  Windows.Devices.SerialCommunication v100.1.0.0, checksum 0x4B336BE9
  Windows.Devices.Spi v100.1.3.0, checksum 0xBDDC51FB
  Windows.Devices.Wifi v100.0.6.0, checksum 0x5AC050C9
  Windows.Storage v100.0.1.0, checksum 0x8D8C8026

++++++++++++++++++++++++++++++++
++        Memory Map          ++
++++++++++++++++++++++++++++++++
  Type     Start       Size
++++++++++++++++++++++++++++++++
  RAM   0x200000c0  0x00020000
  FLASH 0x08000000  0x00400000

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++                   Flash Sector Map                        ++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  Region     Start      Blocks   Bytes/Block    Usage
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      0    0x00010000       1      0x110000     nanoCLR
      1    0x00120000       1      0x1B0000     Deployment
      2    0x002D0000       1      0x040000     Configuration

+++++++++++++++++++++++++++++++++++++++++++++++++++
++              Storage Usage Map                ++
+++++++++++++++++++++++++++++++++++++++++++++++++++
  Start        Size (kB)           Usage
+++++++++++++++++++++++++++++++++++++++++++++++++++
  0x002D0000    0x040000 (256kB)    Configuration
  0x00010000    0x110000 (1088kB)   nanoCLR
  0x00120000    0x1B0000 (1728kB)   Deployment

Deployment Map
Empty

Error messagge:

```
2020-04-02 16:51:57Z [Check and start debug engine on nanoDevice.]
2020-04-02 16:51:57Z [Connect successful.]
2020-04-02 16:51:58Z [Erase deployment area successful.]
2020-04-02 16:51:59Z [nanoDevice is not STM32, skipping flash dump.]
2020-04-02 16:51:59Z [Computing deployment blob.]
2020-04-02 16:52:03Z [Deploying assemblies.]
2020-04-02 16:52:04Z [Incrementally deploying assemblies to the device]
2020-04-02 16:52:05Z [Error writing to device memory @ 0x00120000 (48368 bytes). Error code: 0.]
2020-04-02 16:52:05Z [Error deploying assemblies to the device.]
2020-04-02 16:52:06Z [Deploying assemblies. Second attempt.]
2020-04-02 16:52:07Z [Incrementally deploying assemblies to the device]
2020-04-02 16:52:11Z [Error writing to device memory @ 0x00120000 (48368 bytes). Error code: 0.]
2020-04-02 16:52:11Z [Error deploying assemblies to the device.]
2020-04-02 16:52:11Z [Deployment failed.]
2020-04-02 16:52:11Z [Exception occurred during deployment.
 Deploy failed. 
  
    in nanoFramework.Tools.VisualStudio.Extension.DeployProvider.<>c__DisplayClass25_1.<<DeployAsync>b__6>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in nanoFramework.Tools.VisualStudio.Extension.DeployProvider.<DeployAsync>d__25.MoveNext()]
```

What can i do for deploy project?
Thanks.

**Comment by josesimoes** [comment]
You are using the stable fw version, which doesn't work with the latest VS extension. 
Make sure you either use the preview version or revert the VS extension to <1.2.

For help please use our Discord community. GitHub issues are for confirmed issues with the fw, class libs or tools.
