### ISSUE TITLE
GpioPin.Read() not working (v1.4.1-preview.13)

### ISSUE THREAD

**Issue by opitzh** [nanoframework/Home#594]
## Details about Problem

**nanoFramework area:** Visual studio extension

**VS extension version:** 2019.1.8.9, Windows.Devices.Gpio v1.4.1-preview.13

**Target:**

**Firmware image version:**

**Device capabilities output:**

## Description
GpioPin - Read() method doesn't work with ESP32. I think due to this, also the Toggle() method is not working too. The Read() method returns all the time 0.

## Detailed repro steps so we can see the same problem
[Program.zip](https://github.com/nanoframework/Home/files/4448776/Program.zip)

## Screenshot
![VS](https://user-images.githubusercontent.com/63336732/78754437-c5833180-7977-11ea-83d2-35dc5030e2fc.png)

**Comment by josesimoes** [comment]
@opitzh seems that you're reading from a GPIO that's configured as output. That won't work. You can only read from GPIOs configured as Input.

**Comment by josesimoes** [comment]
BTW, tested with Blinky sample and it's working as expected.
