### ISSUE TITLE
GetCustomAttributes not working

### ISSUE THREAD

**Issue by MateuszKlatecki** [nanoframework/Home#602]
## Details about Problem

**nanoFramework area:** Visual Studio extension (MDP)

**VS version:**

**VS extension version:**

**Target:**

**Firmware image version:**

**Device capabilities output:**

## Description

There are two problems:

- Custom Attributes with constructors not work for classes and methods.
- Custom Attributes with constructors not work for fields if Attribute comes from external library - exception is throwing

## Detailed repro steps so we can see the same problem

See attached projects
[AttProblem.zip](https://github.com/nanoframework/Home/files/4515716/AttProblem.zip)

**Comment by josesimoes** [comment]
@MateuszKlatecki the fix with attributes constructors was implemented for fields only. Nothing with classes and methods... that's why it's failing.

**Comment by MateuszKlatecki** [comment]
So if I understand correctly that there is no support for attribute constructors in System.Reflection.[*]Info (except FieldInfo) and in native methods? Is MDP ready for this?

**Comment by josesimoes** [comment]
That is correct. The major changes with attribute constructors have made those available for fields (which was the task at hand). Nothing was changed in classes and methods.
And yes, the new MDP can handle all this and more.
