### ISSUE TITLE
Socket exception with a determinate configuration of Wifi

### ISSUE THREAD

**Issue by andceoynnova** [nanoframework/Home#606]
Hi,
this is my configuration:

> System Information
> HAL build info: nanoFramework running @ ESP32
>   Target:   ESP32_WROOM_32
>   Platform: ESP32
> 
> Firmware build Info:
>   Date:     Apr 27 2020
>   Type:     MinSizeRel build with IDF v3.3.1
>   Version:  1.4.0.0
>   Compiler: GNU ARM GCC v5.2.0
> 
> OEM Product codes (vendor, model, SKU): 0, 0, 0
> 
> Serial Numbers (module, system):
>   00000000000000000000000000000000
>   0000000000000000
> 
> 
> AppDomains:
> 
> Assemblies:
>   NFAppWifiManager, 1.0.0.0
>   nanoFramework.Runtime.Events, 1.4.2.0
>   nanoFramework.Runtime.Native, 1.2.0.0
>   nanoFramework.System.Collections, 1.0.1.0
>   nanoFramework.ResourceManager, 1.0.0.0
>   Windows.Devices.Wifi, 1.2.0.0
>   Windows.Devices.Gpio, 1.4.1.0
>   System.Net.Http, 1.2.2.0
>   System.Net, 1.4.1.0
>   nanoFramework.System.Text, 1.0.0.0
>   mscorlib, 1.7.2.0
> 
> Native Assemblies:
>   mscorlib v100.4.8.0, checksum 0xE988B5AD
>   nanoFramework.Runtime.Native v100.0.6.1, checksum 0xBD754FED
>   nanoFramework.Hardware.Esp32 v100.0.7.1, checksum 0x1B75B894
>   nanoFramework.Devices.OneWire v100.0.3.4, checksum 0xA5C172BD
>   nanoFramework.Networking.Sntp v100.0.4.4, checksum 0xE2D9BDED
>   nanoFramework.ResourceManager v100.0.0.1, checksum 0xDCD7DF4D
>   nanoFramework.System.Collections v100.0.0.1, checksum 0x5A31313D
>   nanoFramework.System.Text v100.0.0.1, checksum 0x8E6EB73D
>   nanoFramework.Runtime.Events v100.0.7.1, checksum 0x0EAB00C9
>   EventSink v1.0.0.0, checksum 0xF32F4C3E
>   System.Math v100.0.4.4, checksum 0x39DA4F21
>   System.Net v100.1.3.1, checksum 0x1118F266
>   Windows.Devices.Adc v100.1.3.3, checksum 0xCA03579A
>   Windows.Devices.Gpio v100.1.2.1, checksum 0x9A7A2EA4
>   Windows.Devices.I2c v100.2.0.2, checksum 0x79EDBF71
>   Windows.Devices.Pwm v100.1.3.3, checksum 0xBA2E2251
>   Windows.Devices.SerialCommunication v100.1.1.1, checksum 0x82260711
>   Windows.Devices.Spi v100.1.4.1, checksum 0x59B5BFC3
>   Windows.Devices.Wifi v100.0.6.1, checksum 0xDF2FD922
>   Windows.Storage v100.0.2.0, checksum 0x5160A7B6
> 
> 
> 
> ++++++++++++++++++++++++++++++++
> ++        Memory Map          ++
> ++++++++++++++++++++++++++++++++
>   Type     Start       Size
> ++++++++++++++++++++++++++++++++
>   RAM   0x3ffe436c  0x0001bc00
>   FLASH 0x08000000  0x00400000
> 
> 
> 
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> ++                   Flash Sector Map                        ++
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>   Region     Start      Blocks   Bytes/Block    Usage
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>       0    0x00010000       1      0x180000     nanoCLR
>       1    0x00190000       1      0x1B0000     Deployment
>       2    0x00340000       1      0x040000     Configuration
> 
> 
> +++++++++++++++++++++++++++++++++++++++++++++++++++
> ++              Storage Usage Map                ++
> +++++++++++++++++++++++++++++++++++++++++++++++++++
>   Start        Size (kB)           Usage
> +++++++++++++++++++++++++++++++++++++++++++++++++++
>   0x00340000    0x040000 (256kB)    Configuration
>   0x00010000    0x180000 (1536kB)   nanoCLR
>   0x00190000    0x1B0000 (1728kB)   Deployment
> 
> 
> 
> Deployment Map
> Empty

i open a socket with this option:
```
s = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
s.Bind(new IPEndPoint(IPAddress.Any, 15000));
private void RunServer()
        {
            var buf = new byte[20];
            while (true)
            {
                if (s.Available > 0)
                {
                    try
                    {
                        var sender = (EndPoint)new IPEndPoint(IPAddress.Parse("0.0.0.0"), 15000);
                        var received = s.ReceiveFrom(buf, ref sender);
                        string cmd = Encoding.UTF8.GetString(buf, 0, received);
                   }
...
}
```
All run perfectly when i run the device with wifi configuration on AP mode, but if i enable the Wireless80211Configuration when i receive something the compiler thrown an exception
System.Net.SocketException - CLR_E_FAIL (4)

**Comment by josesimoes** [comment]
@andceoynnova this is a question. As stated on the templates GitHub issues are for confirmed issues. If you believe that there is a an issue with the library please add a simple project that reproduces it.
Please post your question on Stackoverflow using nanoFramework tag or on our Discord channels.
