### ISSUE TITLE
Build failing for ChibiOS targets

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#607]
### Details about Problem

**nanoFramework area:** ( Build nf-interpreter )

### Description

Build is failing for ChibiOS based targets after their fix of bug 1093.
Reported on their [forum](http://www.chibios.com/forum/viewtopic.php?f=35&t=5492). Waiting for the fix.

**Comment by networkfusion** [comment]
Fixed?! Just needs syncing with the upstream git...

**Comment by josesimoes** [comment]
Nice! Let's wait for sync time then.

**Comment by josesimoes** [comment]
Fix with https://github.com/nanoframework/ChibiOS/commit/5e78a0f44d2a53d3f204131f3925387e75c69f0c
