### ISSUE TITLE
Deprecation of SPIFFS in favour of littleFS

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#619]
Mark SPIFFS as deprecated (still an option in firmware, although not selected by default) and use littleFS instead. see https://github.com/esp8266/Arduino/pull/7263 for some good reasons why.

**Comment by josesimoes** [comment]
Link to the [littleFS](https://github.com/ARMmbed/littlefs)

**Comment by josesimoes** [comment]
Here's the results of a direct comparison between the two file systems: https://github.com/RIOT-OS/RIOT/pull/8316

**Comment by networkfusion** [comment]
Work on this can be found here: https://github.com/nanoframework/nf-interpreter/tree/develop-littlefs

**Comment by networkfusion** [comment]
Note that chibiOS 20.3.x also supports EFlash subsystem (EFL) http://www.chibios.com/forum/viewtopic.php?f=3&t=4323&sid=15a7802a3245dccb6fe93526752e422a&start=40

**Comment by josesimoes** [comment]
No work has been done to make this change. If you would like to tackle this, please go ahead. We ❤️ PRs!! 😉

**Comment by networkfusion** [comment]
Here was my stab at it: https://github.com/nanoframework/nf-interpreter/commit/df3ba3fa104310317f0aa101615622c257d97eef
