### ISSUE TITLE
STM32F411EDISCOVERY can't use ST_STM32F411_DISCOVERY's image ?	

### ISSUE THREAD

**Issue by maikebing** [nanoframework/Home#623]
I'm download https://bintray.com/nfbot/nanoframework-images-community-targets/ST_STM32F411_DISCOVERY/_latestVersion  and Program to  STM32F411EDISCOVERY , the VS2019's Device Explorer can't found anything ! 
Did I do anything less?

> 
> nanoCLR (Build 1.4.256.0)
> 
> 
> nanoCLR running @ ST_STM32F411_DISCOVERY
> 
> Starting...
> Created EE.
> Started Hardware.
> Create Type System.
> Loading Deployment Assemblies.
> Resolving.
> 
> Total: (0 RAM - 0 ROM - 0 METADATA)
> 
>    AssemblyRef    =        0 bytes (       0 elements)
>    TypeRef        =        0 bytes (       0 elements)
>    FieldRef       =        0 bytes (       0 elements)
>    MethodRef      =        0 bytes (       0 elements)
>    TypeDef        =        0 bytes (       0 elements)
>    FieldDef       =        0 bytes (       0 elements)
>    MethodDef      =        0 bytes (       0 elements)
>    StaticFields   =        0 bytes (       0 elements)
> 
>    DebuggingInfo  =        0 bytes
> 
>    Attributes      =        0 bytes (       0 elements)
>    TypeSpec        =        0 bytes (       0 elements)
>    Resources Files =        0 bytes (       0 elements)
>    Resources       =        0 bytes (       0 elements)
>    Resources Data  =        0 bytes
>    Strings         =        0 bytes
>    Signatures      =        0 bytes
>    ByteCode        =        0 bytes
> 
> 
> Error: a2000000
> Waiting for debug commands...

**Comment by piwi1263** [comment]
Hi @maikebing you have to connect a serial -> usb adapter on USART2. 

PA2 for USART2_TX, PA3 for USART2_RX and a GND wire should do.

If not done already, make sure the board is the only connected and perform a target update as:
![image](https://user-images.githubusercontent.com/10466039/84598196-4293c100-ae69-11ea-816c-089ffd0b88d1.png)
 

It shows in VS 16.6.2 after power cycle of the board:
![image](https://user-images.githubusercontent.com/10466039/84598564-e9795c80-ae6b-11ea-8477-d57e27e67bb9.png)

**Comment by maikebing** [comment]
Thank you so much.
