### ISSUE TITLE
Debug.Writeline prevents re-programming

### ISSUE THREAD

**Issue by FraserElectronics** [nanoframework/Home#637]
### Details about Problem
I have a tight loop where I am calling Debug.Writeline to output debugging information.
I now find that once I have programmed and run the firmware I can no longer re-program my firmware from Visual Studio. Although it still detects the target in Device Explorer it says "No response on COM8".
The only solution is to do a full chip erase and reprogram the bootloader and CLR.

**Target:**
ST Nucleo144 F746ZG

**Firmware image version:**
1.4.590.0

Worked before? If so, with which nanoFramework image version:
Don't know.

**Device capabilities output:**

### Description

Suspect that continuously writing to debug output if preventing other code from running or causing something to timeout ?

### Detailed repro steps so we can see the same problem

Here is the code that causes problems:
```csharp
            long ticksnow;

            while ( true )
            {
                //
                // If we see a gap in the incoming serial data of 1.5 character (byte) times
                // then we will attempt to process what we have received so far.
                //
                ticksnow = DateTime.UtcNow.Ticks;
                Debug.WriteLine( ( ticksnow - _lastIncomingDataTick ).ToString() );
                if ( ( ticksnow - _lastIncomingDataTick ) > ( _halfCharTickTime * 3 ) )
                {
                    lock ( _incomingFrame )
                    {
                        if ( _incomingReceived > 0 )
                        {
                            ProcessModbusFrame();
                            _incomingReceived = 0;
                        }
                    }
                }
            }
```

### Expected behaviour

I expect to be able to rebuild and reprogram my code endlessly without having to reflash the whole device.

**Comment by josesimoes** [comment]
Is the above running on main() or on its own thread?

**Comment by FraserElectronics** [comment]
It is running in its own thread.

Andy

Sent from my iPhone

On 11 Aug 2020, at 11:23, José Simões <notifications@github.com> wrote:

﻿

Is the above running on main() or on its own thread?

**Comment by steffalk** [comment]
Hello @FraserElectronics, could it be that you lock(_incomingFrame) nested? Aka something like lock(_incomingFrame) {... lock(_incomingFrame) {...} ...}? Even if both locks happen on separate threads - so you suffer from some deadlock?
Best Regards, Stefan

**Comment by FraserElectronics** [comment]
It happens even if I am not sending data so _incomingReceived is always zero. Also, I see the debug text scrolling on screen which means I don’t have a deadlock on my lock.

Andy

Sent from my iPhone

On 11 Aug 2020, at 23:22, Stefan Falk <notifications@github.com> wrote:

﻿

Hello @FraserElectronics<https://github.com/FraserElectronics>, could it be that you lock(_incomingFrame) nested? Aka something like lock(_incomingFrame) {... lock(_incomingFrame) {...} ...}? Even if both locks happen on separate threads - so you suffer from some deadlock?
Best Regards, Stefan

**Comment by steffalk** [comment]
So should we be able to reproduce the issue just by using while (true) {Debug.Writline("something");}? On what kind of board and firmware did that occur please?

**Comment by FraserElectronics** [comment]
It is running on the Nucleo-F746ZG

Andy

Sent from my iPhone

On 12 Aug 2020, at 09:42, Stefan Falk <notifications@github.com> wrote:

﻿

So should we be able to reproduce the issue just by using while (true) {Debug.Writline("something");}? On what kind of board and firmware did that occur please?

**Comment by josesimoes** [comment]
Cant' reproduce this... it must be something in your code.

Please attach a project with minimal code that reproduces the behaviour you're describing.
