### ISSUE TITLE
Firmware 1.6.X.X shows error System.Net.Security.SslNative::SecureClientInit when performing HTTPS request AND SD card mounted on ESP32. Works fine in FW<1.4.0.107

### ISSUE THREAD

**Issue by jefmad** [nanoframework/Home#672]
## Details about Problem

**Target:**
ESP32_WROOM_32

**Firmware image version:**
Error is with FW greater than 1.4.0-preview.107

Worked before? If so, with which nanoFramework image version:
1.4.0-preview.107

**Device capabilities output:**
Not relevant, see samples below.

### Description

Hello team,
I managed to target a bit more what the issue with this SSL error message is.
To make it simple, using a ESP32, SSL requests fail only when SD card is mounted and only in all the FW after the version 1.4.0-preview.107, including the last one : 1.6.1-preview.59.

New samples are attached (I remove the web server which is not the cause), they are simple to understand and reproduce the issue.

For information, the certificate is NOT on the SD card, there is no action to SD card apart from mounting it.

Maybe the issue about SSL appeared because of this modification:
Improvements in SSL accept handler [\#62](https://github.com/nanoframework/lib-nanoFramework.System.Net.Http/pull/62)

### Detailed repro steps so we can see the same problem

!! Note that if during tests your device gets the error : System.Net.Security.SslNative::SecureClientInit, the only way to get rid of it is to flash the device. Once this error is obtained, the following test are not accurate anymore, flashing is needed to go on.

Step to reproduce the issues (The two samples are identical, the difference is version of assemblies :

1 - With the sample KO - 1.6.1.59 :
[KO - 1.6.1.59.zip](https://github.com/nanoframework/Home/files/6118163/KO.-.1.6.1.59.zip)

**•	1st SSL request is OK
•	Mounting the SD card
•	2nd SSL request is KO and the error is :**
![image](https://user-images.githubusercontent.com/56963506/110680139-86d5a700-81d8-11eb-9cd8-5c9b30b40e11.png)

           Fail with this error in System.Net.HttpWebRequest.cs
            on
            sslStream.AuthenticateAsClient(m_originalUrl.Host, null, m_caCert, m_sslProtocols);

            **The issue is in Sslstream.cs on line 131:
            _sslContext = SslNative.SecureClientInit((int)enabledSslProtocols, (int)_sslVerification, certificate, ca);**

2 - With the sample OK - 1.4.0.107 : SSL requests work with or without SD card mounted.
[OK - 1.4.0.107.zip](https://github.com/nanoframework/Home/files/6118165/OK.-.1.4.0.107.zip)

For both samples, you need to enter your Wifi information and for the sample KO - 1.6.1.59, pay attention to the timer in the execution of the second debugging. If the timer is too short, after the 1st debugging, you will get the System.Net.Security.SslNative::SecureClientInit error and you need to flash the device again. As soon as you get this error, you’ll have it forever when issuing SSL request.

### Expected behaviour

What is expected is that sample with FW 1.6.X.X runs without error when performing ssl request as the sample using FW 1.4.0.107

### Screenshot
See samples

**Comment by jefmad** [comment]
In order not to be closed after having been marked as stale... Need to test persistent connection and System.Io.FileSystem

**Comment by josesimoes** [comment]
Can't reproduce.

Everything seems to be working as expected with fw and libraries released in this date.

Because I have a WROVER KIT, I had to comment out the SPI config lines and replace the SD card mount with this one:
`SDCard.MountMMC(false);`

I even replaced the HTTP files that you have in the project with the HTTP.Client library.

Made  calls in a row to `Perform_SSL_HTTPRequest()`. All good except a parse error from the content.

**Comment by jefmad** [comment]
Ok, thanks for the feedback and your tests !  The issue is obtained on ESP32 WROOM-32, not on ESP-WROVER.

After your comment, I thought that SPI config could be the problem, and I tested with another SPI config lines  : exactly the SPI1 config defined here : https://docs.nanoframework.net/content/esp32/esp32_pin_out.html (// Default pins for "SPI1" : Mosi=23  Miso=25  Clk=19) and still the same result : if not mounting SD card via the command SDCard.MountSpi("SPI1", XX); the SSL requests are performed without any problem, as soon as the SD card is mounted, SSL requests fail with the error SecureClientInit.

The parse error are linked to the content and I got them sometimes, it's ok with this. And the http file in the project were present to debug more deeply :-)

**It would be nice if another person with a ESP32 WROOM-32 and an external SD card could test**. I tested on two ESP32 WROOM-32 and it was working before FW 1.4.0-preview.107 and not working anymore... Thanks

**Comment by josesimoes** [comment]
Is this still an issue?

**Comment by jefmad** [comment]
I have not tested with latest FW, but to me my last comment is still valid : **It would be nice if another person with a ESP32 WROOM-32 and an external SD card could test.** SPI config could be the problem
Is there any improvement in the availability of System.IO for ESP32 ? This could be an option that allow to close this issue

**Comment by Ellerbach** [comment]
So I finally manage to reproduce the issue. It's **only** happening with ESP32_WROOM, seems only in wifi.
* issue is yes, related to SDCard in this configuration.
* When mounting the SD Card, a lot of memory is probably allocated and once you want to use SSL Stream, quite some allocated as well
* All up, that *most likely* creates a memory issue somewhere
* The fact that the problem stays even after a soft reset is *most likely* related to the ESP32 part directly. So not really on the native side written in nf-interpreter neither the C# classes.
Of course, a deeper investigation will be needed!

**Comment by jefmad** [comment]
I'm adding to your conclusion that the problem occurs with SSL stream and HttpWebRequest (using SSL), and that the issue appeared after FW 1.4.0.107 on ESP32_WROOM.  I was pointing this : "Improvements in SSL accept handler #62" https://github.com/nanoframework/nanoFramework.System.Net.Http/pull/62 because the change matches the FW, maybe it could be an hint for deeper investigation. Thanks for your help @Ellerbach !

**Comment by Ellerbach** [comment]
@jefmad after more tests, you'll have issues as well with the LiLyGo and Ethernet. Same issue. And you don't even need to have SD Card, issue will happen sooner or later.

**Comment by jefmad** [comment]
Thanks @Ellerbach . Would you have some time to test and verify the other point in my statement : flashing your device with FW 1.4.0.107 and run the second sample above and ensure that the problem is not here.
This would narrow the moment the problem appeared and confirm where to look and investigate deeper.

Actually my whole home automation project (SD, SSL request, Web server...) is stuck with FW 1.4.0.107 because the bug detailed above is not present, but I'm missing some nice feature like Infra red or others cool things / improvments...

**Comment by josesimoes** [comment]
Waiting for migration to next IDF.

**Comment by jefmad** [comment]
Since migration of nanoff to cloudsmith, I'm sharing the sources of the Image ESP32_WROOM_32-1.4.0-preview.107 that is the last not having the issue detailed here. 
[ESP32_WROOM_32-1.4.0-preview.107.zip](https://github.com/nanoframework/Home/files/6825805/ESP32_WROOM_32-1.4.0-preview.107.zip)
Use --clrfile with nanoff

**Comment by josesimoes** [comment]
@jefmad can you try with the latest fw? The TLS buffer issue has been fixed.

**Comment by jefmad** [comment]
@josesimoes Sure, I'll try if it solve the issue, can it wait 2 weeks? I'll give you my feedback

**Comment by Ellerbach** [comment]
On my side I can confirm everything is now working perfectly. I did test the scenario with an ESP32 (dev kit, no psram) connected in Wifi using the Azure IoT DPS service with certificate. So it requires a cert2 certificate with private encrypted key, 2 public one, 2 MQTT TLS connection on 2 different servers in a raw. Pure love, all worked like a charm!

**Comment by jefmad** [comment]
Hi, after a quick test with an ESP32 WROOM-32 having FW 1.6.5.3 (tested also with FW 1.6.6 preview 530) , running the SSL sample (SecureClient) I have the same issue than detailed above     ++++ System.Net.Security.SslNative::SecureClientInit [IP: 0000] ++++, so I haven't tried to see if it's working with mounting a SD card...
@Ellerbach Can you share your test program, or is this the SSL sample ? Which FW are you running ?

**Comment by Ellerbach** [comment]
@jefmad I've been using the basic example. Also I'm using quite intensively TSL with MQTT.
Really all worked. Haven't been testing SSL with the latest framework.
Make sure you're **not** using the BLE version. Just use the normal ESP32_WROOM version.
Happy to do a quick screen sharing, seems like we're both French, can be faster. Ping me on Discord.

**Comment by jefmad** [comment]
I confirm that SSL sample and HTTPS sample both work with FW 1.7.0.2, my issue was a matter of PEM certificates to update in the samples. But I cannot test SSL + SD card mounted due to this issue that I'm also reproducing : https://github.com/nanoframework/Home/issues/795
And it seems that System.IO does not have functionality to mount SD card on specific SPI Pins

**Comment by josesimoes** [comment]
OK. Thanks for the feedback.

That will be addressed in that other issue.


As it seems to be fixed I'm closing it. Feel free to reopen if needed.

**Comment by jefmad** [comment]
Hi @josesimoes , I saw you closed this issue. But to me its status should be blocked (with a reference to https://github.com/nanoframework/Home/issues/795), because the original issue was SSL error when SD card was mounted and nowadays there is no way to mount SD card on ESP 32, so I've not been able to test if the issue is solved. I will be able to test as soon as issue 795 is solved...

**Comment by josesimoes** [comment]
It's now possible to mount SDCard on ESP32 and combination of network + TLS has been improved.
Closing this now, feel free to reopen if needed.
