### ISSUE TITLE
UnitTestInitLocalTests.SystemType1_GetType_Test fails

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#707]
### Details about Problem

**nanoFramework area:** (mscorlib)

### Description

Test is failing. Need to fix code in mscorlib.

### Screenshot

![image](https://user-images.githubusercontent.com/1881520/109958979-c125dc80-7cde-11eb-84ee-13728888895d.png)

**Comment by SandorDobos** [comment]
this test is green for me.
my nanoframework.TestFramework is at b0f34e49da66edfc066793005e7c45217266fed4.

**Comment by Ellerbach** [comment]
> this test is green for me.

The failing ones are the ValueArrayTypes. In short GetType("System.Int32[]") and any other with array is not working
![image](https://user-images.githubusercontent.com/8145578/110428553-ba65e380-80a9-11eb-92a4-e04ffa86c0db.png)

**Comment by josesimoes** [comment]
Fixed!
