### ISSUE TITLE
DebugLogger class does not write to Debug window

### ISSUE THREAD

**Issue by edleno2** [nanoframework/Home#737]
### Details about Problem

**nanoFramework area:** DebugLogger class in nanoFramework.Logging

**VS version:** (2019)

**VS extension version:**

**Target:**

**Device capabilities output:**

### Detailed repro steps so we can see the same problem

1.  Clone user repository for the problem: [Link ](https://github.com/edleno2/DependencyProblemTest)

2.  Run the code under the debugger on a nanoFramework device using a DEBUG build
3.  The Debug Output window in Visual Studio will display the message "Hello from Debug.WriteLine!" but none of the output from the DebugLogger will appear

### Other suggested things
Problem likely that DebugLogger.cs uses Debug.WriteLine, but when built in RELEASE mode as a Nuget package that statement is no-op'd by the compiler.

### Expected behavior
All of the DebugLogger messages should appear in the Debug Output window of Visual Studio

#### Sample Project
https://github.com/edleno2/DependencyProblemTest

### Screenshot
![Debug logger problem sample](https://user-images.githubusercontent.com/22162851/116910754-e362aa80-abfa-11eb-9453-3f66f3c22a4a.png)

### Additional context
Discussed in the Discord channel #class-libraries

### I've made an effort to fix the bug
PR to follow.

**Comment by josesimoes** [comment]
[ ] Add `nanoFramework.Logging` assembly to the `InternalsVisibleTo` of mscorlib.
[ ] In `nanoFramework.Logging` code replace `Debug.WriteLine` with `Console.WriteLine`
