### ISSUE TITLE
Flash using --fwversion doesn't work with cloudsmith.io

### ISSUE THREAD

**Issue by edleno2** [nanoframework/Home#745]
### Details about Problem

**nanoFramework area:** nanoFirmwareFlasher

**Target:** Noted with esp32, but probably applies to all targets

### Description

When flashing firmware and specifying --update and --fwversion only the latest firmware will be downloaded and applied.  It may even be named using the version provided via --fwversion, but the zip file downloaded was in fact the latest and not the version specified.  
### Detailed repro steps so we can see the same problem

1. Run nanoff command "nanoff --platform esp32 --serialport com3 --fwversion 1.6.4-preview.183 --update".  .183 is NOT the latest version.  If you delete the target directory in c:\user dir\.nanoFramework (the cache) before running you will see a zip file with the --fwversion name on it.  But if you check the dates on the files in the zip file they will be from the latest version in cloudsmith.

2. Use Device Explorer/Device Capability and look at the version of the firmware - it will be the latest and not the specified --fwversion.

...

### Other suggested things

Possibly due to the API command used in FirmwarePackage.cs line 80: 
string requestUri = $"{_cloudsmithPackages}/{repoName}/?page=1&query={_targetName} latest";
### Expected behaviour

Downloaded zip file should be in the cache and contain the files from the selected version

**Comment by josesimoes** [comment]
Wasn't this addresses in nanoframework/nanoFirmwareFlasher#51?

**Comment by edleno2** [comment]
> Wasn't this addressed in [nanoframework/nanoFirmwareFlasher#51](https://github.com/nanoframework/nanoFirmwareFlasher/pull/51)?

Oops...yes it was!  I checked for a duplicate issue, but not if there was PR for this.  I'll just close this issue.
