### ISSUE TITLE
Port name mismatch on System.IO.Port 

### ISSUE THREAD

**Issue by up-streamer** [nanoframework/Home#761]
### Details about Problem

**nanoFramework area:** (C# code )

**VS version:** (2019 )

**VS extension version:**

**Target: ESP32**

### Description
It is not possible to declare SerialPort as shown on screen shot. Please note "portName" on the Insert window and "PortName" on the code.

### Detailed repro steps so we can see the same problem

Try declare SerialPort as per screen shot.

### Expected behaviour
It should be possible to declare port name in both cases. In ( ) or as a parameter list. 

### Screenshot
![Port issue 1a](https://user-images.githubusercontent.com/38735560/120418580-2d909600-c337-11eb-8473-c0d2ef30d1e1.jpg)

**Comment by Ellerbach** [comment]
That is on purpose. There is no constructor taking no portName argument.

**Comment by josesimoes** [comment]
Absolutely! Unlike the full .NET API, we don't have the constructor _without_ the COM port name. We have to keep things simple and this is one of those choices. 😉

**Comment by up-streamer** [comment]
Understood.
It is not a real issue anyway... 
Thanks.
