### ISSUE TITLE
Removing IO-Expander_MCP23017 from nf-Community-Contribution as present in nanoFramework.IoT.Device

### ISSUE THREAD

**Issue by Ellerbach** [nanoframework/Home#765]
### Details about Problem

**nanoFramework area:** C# code

### Description

- Removing IO-Expander_MCP23017 from nf-Community-Contribution as present in nanoFramework.IoT.Device
- Larger family in the new repository.

Tagging @LordAsdi as original author.

**Comment by josesimoes** [comment]
@Ellerbach hasn't this been moved already?

**Comment by networkfusion** [comment]
I think so: https://github.com/nanoframework/nf-Community-Contributions/commit/bb3d0e7ae2373a22470bd69448001cfab23d50e9 . Given that, I am closing... Feel free to reopen if not.
