### ISSUE TITLE
Removing RTC_DS3231 from nf-Community-Contribution as present in IoT.Device

### ISSUE THREAD

**Issue by Ellerbach** [nanoframework/Home#766]
### Details about Problem

**nanoFramework area:** C# code

### Description

- Removing RTC_DS3231 from nf-Community-Contribution as present in IoT.Device
- New binding contains more RTC as well

Tagging original author @hbraasch

**Comment by josesimoes** [comment]
Device is now at https://github.com/nanoframework/nanoFramework.IoT.Device/tree/develop/devices/Rtc
