### ISSUE TITLE
Removing ShiftRegister-74HC595 from nf-Community-Contribution as existing in IoT.Device

### ISSUE THREAD

**Issue by Ellerbach** [nanoframework/Home#767]
### Details about Problem

**nanoFramework area:** C# code

### Description

- Removing ShiftRegister-74HC595 from nf-Community-Contribution as existing in IoT.Device

Tagging original author @Dweaver309

**Comment by Dweaver309** [comment]
Thanks Laurent for all your great contributions to the project. I have not
tested the code for years.

Thanks again for the help

**Comment by josesimoes** [comment]
Device is now at https://github.com/nanoframework/nanoFramework.IoT.Device/tree/develop/devices/ShiftRegister
