### ISSUE TITLE
Removing ULN2003 from nf-Community-Contribution as already present in new IoT.Device

### ISSUE THREAD

**Issue by Ellerbach** [nanoframework/Home#768]
### Details about Problem

**nanoFramework area:** C# code 

### Description

- Removing ULN2003 from nf-Community-Contribution as already present in new IoT.Device

Tagging original author @hbraasch

**Comment by josesimoes** [comment]
Device is now at https://github.com/nanoframework/nanoFramework.IoT.Device/tree/develop/devices/Uln2003
