### ISSUE TITLE
ToString() fails with null object

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#772]
### Details about Problem

**nanoFramework area:** (mscorlib)

### Description
Calling ToString() with a null object throws an exceptio.

### Detailed repro steps so we can see the same problem

	object iAmNull = null;
	Debug.WriteLine($"This is supposed to work: {iAmNull}");

**Comment by edleno2** [comment]
This may have come from my cleanup of unit tests.  I'll include testing it along with the String.Format issue, but submit a separate PR just for this issue.   I had to test on .net core - didn't think this would work this way!

**Comment by edleno2** [comment]
I believe it's not ToString() but String.Format that is supposed to accept null arguments.  I do remember changing that behavior so I'll have to go back to which cases should work and which should get a null exception.

**Comment by edleno2** [comment]
Waiting for checks to complete.  I'll send for review tomorrow morning if all of the checks pass.
