### ISSUE TITLE
Wrong socket exception value returned

### ISSUE THREAD

**Issue by martin-kuhn** [nanoframework/Home#775]
### Details about Problem

**Target:**
STM32F769I-DISCO
(the issue has also been detected on a custom STM32F427 based mcu board)

**Firmware image version:**
1.6.5-preview.337
(it's also the case with older firmware images)

### Description
The target is communicating through multiple tcp sockets without any problems. When we then open an additional socket and try to connect to an endpoint which is not available on the network, then a socket exception occurs. Of course, this is expected. But the error code which is returned, is obviously wrong.
The screenshots show that the mcu tries to connect to 80.74.153.100 and then sends 6 retransmission packets. After that, the connection attempt is aborted and the socket exception 10035 (WOULDBLOCK) is returned.
I had a closer look at the socket structure while debugging the firmware. Actually, the netconn structure inside the socket structure has a last_err field which contains the LWIP error. After the connection abort, last_err is set to -13 (ERR_ABRT) which makes sense. But the throwOnError function gets the err field of the socket structure which seems not to be updated correctly with the value of the netconn structure. This one still contains the error value of the connect function call, which reported INPROGRESS (10037) and this is later mapped to WOULDBLOCK (10036).

### Detailed repro steps so we can see the same problem

1. Connect the board to a local network and set an IP.
2. Create a new socket and try to connect to an endpoint which is not available on the network.
3. Look at the error code in the debug output. It will be set to EWOULDBLOCK instead of ECONNABORTED.

IPHostEntry hostEntry = Dns.GetHostEntry("80.74.153.100");
IPEndPoint myEndpoint = new IPEndPoint(hostEntry.AddressList[0], 80);
try
{
    thirdSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.IPv4);
    thirdSocket.Connect(myEndpoint);
}
catch (SocketException ex)
{
    Console.WriteLine("Failed to connect to socket (Error Code: " + ex.ErrorCode + ")");
}
finally
{
    if (thirdSocket != null)
    {
        thirdSocket.Close();
        thirdSocket = null;
    }
}

### Expected behaviour

The error code should be set to ECONNABORTED instead of EWOULDBLOCK.

### Screenshot
<img width="947" alt="Wireshark_Retransmission" src="https://user-images.githubusercontent.com/54800166/121704823-65849f80-cad4-11eb-9075-102773ef9d86.PNG">
<img width="382" alt="VS_DebugOutput" src="https://user-images.githubusercontent.com/54800166/121704843-6a495380-cad4-11eb-9d81-27a54642cd33.PNG">

**Comment by josesimoes** [comment]
@martin-kuhn thanks for the detailed error report.
You seemed to have reached the root cause of the problem and know what need to be fixed.
Can you please submit a PR with the fix?
