### ISSUE TITLE
Contains("<<Something") doesn't return true while it should

### ISSUE THREAD

**Issue by Ellerbach** [nanoframework/Home#779]
### Details about Problem

**nanoFramework area:** C# code

**VS version:** (2017 | 2019 )

**VS extension version:**

**Target:**

**Device capabilities output:**

### Description

Issue with string.Contains for a specific character string.

### Detailed repro steps so we can see the same problem

```csharp
const string C9PatternMainStyle = "<<Main>$>g__";
string mtName = "<<Main>$>g__MethodCalbackTest|0_3";
if (mtName.Contains(C9PatternMainStyle))
{
  // We should arrive here but Contains doesn't find it!
}
```

Notes:

- Works: `mtName.Contains("Main>$>"))`
- Does not work: `mtName.Contains("<<Main"))`

**Comment by josesimoes** [comment]
Our API currently has no `Contains(...)` and friends. We should look into adding these. 
Most of them can (are) pure C# code, so they won't "cost" anything in native size increase.

**Comment by Ellerbach** [comment]
You're right :-) My bad :-D It's an extension I have and the issue is in the extension! Found my issue.

**Comment by josesimoes** [comment]
Almost ready. Just adding a pile of unit tests 😜
