### ISSUE TITLE
nanoFramework.Tools.MetadataProcessor.MsBuildTask.dll is missing

### ISSUE THREAD

**Issue by romfir** [nanoframework/Home#788]
### Details about Problem

**nanoFramework area:** Visual Studio extension

**VS version:** VS 2019 Enterprise Preview 16.11.0 preview 2.0 and Enterprise 16.9.4

**VS extension version:** 2019.6.0.60

### Description

I've installed .NET nanoFramework VS2019 Extension, but file ```nanoFramework.Tools.MetadataProcessor.MsBuildTask.dll``` is missing from ```C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\nanoFramework\v1.0```
![image](https://user-images.githubusercontent.com/33402460/124668192-c96e6e00-deb0-11eb-9869-16382808c493.png)
I've manually build metadata-processor from source and copied all .dlls and it is now working.

Also when I manually inspected .vsix installer, file was also not present there.
![image](https://user-images.githubusercontent.com/33402460/124668619-6b8e5600-deb1-11eb-8285-7b9e3ae842a0.png)

### Detailed repro steps so we can see the same problem

1. Install VS2019 extension

2. Create empty project
3. Try to build it

**Comment by josesimoes** [comment]
Problem identified. Fix is on the way!
