### ISSUE TITLE
nanoFramework.System.Text.RegularExpressions requires a non-existent dependency

### ISSUE THREAD

**Issue by devbotas** [nanoframework/Home#800]
### Details about Problem

**nanoFramework area:** (C# code | **Nuget packages** | Community contributions | Documentation )

**VS version:** (2017 | 2019 )

**VS extension version:**

**Target:**

**Device capabilities output:**

### Description
I think it is a typo in NuGet manifest file (dependency version should be 1.2.0, not 11.2.0), see the picture. 

### Screenshot
![image](https://user-images.githubusercontent.com/71982803/127828157-e50b9a1e-632f-4cd0-9442-f46aa94bc170.png)

**Comment by josesimoes** [comment]
Fixed in https://github.com/nanoframework/System.Text.RegularExpressions/commit/167f20ad6a12d1c4e73280fa4c7f3bc25dce5bb7

**Comment by josesimoes** [comment]
Thanks for reporting and fix suggestion! 👍🏻
