### ISSUE TITLE
Stable version of nanoFramework.M2Mqtt still references a preview lib

### ISSUE THREAD

**Issue by devbotas** [nanoframework/Home#801]
### Details about Problem

**nanoFramework area:** ( Nuget packages)

### Description
nanoFramework.M2Mqtt version 5.0.0, which is a stable release, still references a single preview dependency, see the pic. 

### Screenshot
![image](https://user-images.githubusercontent.com/71982803/127834563-7ab36e25-b937-45b6-8b98-1e8ccf86bb2a.png)

**Comment by josesimoes** [comment]
Fixed with https://github.com/nanoframework/nanoFramework.m2mqtt/commit/112afdd4439cbbd4a4d1ba5d83bf46d9d5623371

**Comment by josesimoes** [comment]
Thanks for reporting and fix suggestion! 👍🏻
