### ISSUE TITLE
nanoFirmwareFlasher wrong message in ESP32 without BlueTooth.

### ISSUE THREAD

**Issue by up-streamer** [nanoframework/Home#806]
### Details about Problem

**nanoFramework area:** ( Visual Studio extension | Other tools )

**VS version 2019:**

**VS extension version Latest:**

**Target ESP32:**

**Firmware image version Latest:**

**Device capabilities output:**

### Description

nanoFirmwareFlasher is "saying": 
"Seems that you're about to use a firmware image that includes Bluetooth, but the" 
"connected device does have support for it. You should use a target without BLE in the name" 
and should "say: 
"connected device does NOT have support for it. You should use a target without BLE in the name" 

### Detailed repro steps so we can see the same problem

1. It is on line 145 of nanoFirmwareFlasher/Esp32Operations.cs 

2.

...

### Expected behaviour

Message should indicate correct behave. 

### Make an effort to fix the bug

Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by josesimoes** [comment]
Can you please copy here the output of nanoff that you are seeing?
