### ISSUE TITLE
Need a way to mount SD Card reader on STM32

### ISSUE THREAD

**Issue by Ellerbach** [nanoframework/Home#808]
**nanoFramework area:** (Hardware/target board)

### Is your feature request related to a problem? 

Not all the STM32 card reader attached has a detection pin. So it makes it impossible to use when not forcing to mount the SD Card.

It would be perfect to add this API which does exist on ESP32 for STM32 (and other devices).

The best place for that may be in the new System.IO.File* that is being currently ported.

### Describe the solution you'd like

Have a way to mount manaly an SD Card on STM32

### Describe alternatives you've considered

Use a pin like an input to simulate the card insertion but that is not very practical

**Comment by josesimoes** [comment]
Not implemented
