### ISSUE TITLE
WebServer library not recognizing routes with attributes

### ISSUE THREAD

**Issue by WilliamAltemus** [nanoframework/Home#812]
### Details about Problem

**nanoFramework area**
C# code | Nuget packages

**VS version**
Microsoft Visual Studio Community 2019
Version 16.11.1

**VS extension version**
2019.6.0.77

**Target**
Freenove ESP32-WROVER-DEV

### Description
WebServer library not recognizing routes with attributes

### Detailed repro steps so we can see the same problem

Installed libraries: 
nanoFramework.CoreLibrary
nanoFramework.NetWorkHelper
nanoFramework.Runtime.Events
nanoFramework.System.Collections
nanoFramework.System.Device.Gpio
nanoFramework.System.IO.Ports
nanoFramework.System.Net
nanoFramework.System.Net.Http.Server
nanoFramework.System.Text
nanoFramework.System.Threading
nanoFramework.WebServer
nanoFramework.Windows.Devices.Wifi
nanoFramework.Windows.Storage
nanoFramework.Windows.Storage.Streams

Followed the WebServer.GpioRest sample as a general guide

### Expected behaviour
It fires the route method when I use a route without attributes (//192.168.1.8/led) but not when I use a route with attributes (//192.168.1.8/led/on)

Case: //192.168.1.8/led 
Debug output: Handling request led

Case: //192.168.1.8/led/on 
Debug output: <none>

No errors reported

#### Sample Project

```
using (WebServer server = new WebServer(80, HttpProtocol.Http, new Type[] { typeof(ControllerGpio) }))
{
    // Start the server.
    server.Start();

    Thread.Sleep(Timeout.Infinite);
}
```

```
class ControllerGpio
{
    private static GpioController _gpioController = new GpioController();

    private static int ledPin = 2;

    [Route("led")]
    public void Led(WebServerEventArgs e)
    {
        try
        {
            var rawUrl = e.Context.Request.RawUrl.TrimStart('/');
            Debug.WriteLine($"Handling request {rawUrl}");
            var args = rawUrl.Split('/');
            if (args.Length < 2)
            {
                WebServer.OutputHttpCode(e.Context.Response, HttpStatusCode.BadRequest);
                return;
            }

            // If the pin is not open
            if (!_gpioController.IsPinOpen(ledPin))
            {
                // Open pin
                _gpioController.OpenPin(ledPin);
                // Set pin mode to output
                _gpioController.SetPinMode(ledPin, PinMode.Output);
            }

            if (args[1].ToLower() == "on")
            {
                _gpioController.Write(ledPin, true);
            }
            else if (args[1].ToLower() == "off")
            {
                _gpioController.Write(ledPin, false);
            }
            else
            {
                WebServer.OutputHttpCode(e.Context.Response, HttpStatusCode.BadRequest);
                return;
            }

            WebServer.OutputHttpCode(e.Context.Response, HttpStatusCode.OK);
        }
        catch (Exception)
        {
            WebServer.OutputHttpCode(e.Context.Response, HttpStatusCode.BadRequest);
        }
    }
}
```

**Comment by Ellerbach** [comment]
@WilliamAltemus I checked and it's on purpose.
Let me give you few explanations:

* /led/on is different controller than /led
* if you wan to use the /led/on and /led/off, you have 3 options:
  * either don't use the controller pattern but uses the event pattern
  * either customize in the same controller 2 entry points with /led/on and /led/off
  * either use the controller pattern with URL parameters: /led?on or /led?off or even /led?s=on or /led?s=off

In HTML, the parameter in a url is defined with ? not /
/ is defined for the folders and route which in the case of /led/on is a special route which is different than /led and different from /led/off

I hope this is clear explanation. Happy to have a more detailed conversation.

**Comment by Ellerbach** [comment]
The event pattern is the one describe in the examples, you'll get just the raw URL, up to you to do whatever you want.

If you still want to use controller and have those 2 different routes in your controller, then this will work:

```csharp

        [Route("led/on")]
        public void LedOn(WebServerEventArgs e)
        {

        }

        [Route("led/off")]
        public void LedOff(WebServerEventArgs e)
        {

        }

```

If you want to use the parameter pattern, then url should be /led?on or /led?off for example. Your code will then adjust to:

```csharp
var args = rawUrl.Split('?'); // so ? instead of /
```

**Comment by WilliamAltemus** [comment]
This is a perfect explanation of what was happening.  Thank you!

**Comment by Ellerbach** [comment]
> This is a perfect explanation of what was happening. Thank you!

Great!

Also check the Person samples, you'll see that phenomenon. And that you can even have route for GET, POST or anything else: https://github.com/nanoframework/Samples/blob/main/samples/Webserver/WebServer.Sample/ControllerPerson.cs
