### ISSUE TITLE
Remove NFMDP_PE_LoadHints group from all class libraries

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#817]
### Details about Task

**nanoFramework area:** class libraries

### Description
`NFMDP_PE_LoadHints` aren't required anymore. Need to remove the respective ItemGroup from all class libraries. See [here](https://github.com/nanoframework/System.IO.FileSystem/commit/00d3a6c9fe8fa4c33ffbffc60633e7f9885cb664) for reference.

**Comment by networkfusion** [comment]
I think I have now caught all of the Pokemon... please let me know if you think I have missed any!

**Comment by josesimoes** [comment]
Well done @networkfusion ! All PRs reviewed and merged. Thanks for taking care of this.
