### ISSUE TITLE
Unloaded project still active project for deployment

### ISSUE THREAD

**Issue by TerryFogg** [nanoframework/Home#847]
### Details about Problem

**nanoFramework area:** ( Visual Studio extension  )

**VS version:**

**VS extension version:**

**Target:**

**Firmware image version:**

**Device capabilities output:**

### Description

With a project with standard nanoFramework project and additional class libraries, when the standard application is unloaded the highlighted project(startup project) becomes one of the class libraries. Adding a new standard project does not make it the startup project. Starting debug, deploys the last project ( currently unloaded)

### Detailed repro steps so we can see the same problem

1. Add class library(ies)
2. Add blank "hello nanoFramework" named Test.
3. Compile, build deploy Test
4. Check works ok.
5. Unload project Test.
6. Add another standard nanoFramework application.
7. Note, class library is "bolded" as startup project
8. Try to debug, Test project is deployed and run successfully....

### Expected behaviour

Since the current startup project is now a class library, it should message with this and stop until a change to the startup project is made

### Screenshot

In this example, Test was deployed and run.

![image](https://user-images.githubusercontent.com/12385835/135809272-68e307db-67d4-416c-a6f7-2adf63aeeec8.png)

### Additional context

Not a high priority issue

**Comment by josesimoes** [comment]
The described behavior it's coming from Visual Studio. Our project system can override or circumvent that...
