### ISSUE TITLE
Unloaded class library referenced in project to deploy could have a improved message

### ISSUE THREAD

**Issue by TerryFogg** [nanoframework/Home#848]
### Details about Problem

**nanoFramework area:** ( Visual Studio extension  )

**VS version:**

**VS extension version:**

**Target:**

**Firmware image version:**

**Device capabilities output:**

### Description

If a nanoFramework application references a class library through add reference not through nuget package, and that class library is unloaded , future deployment fails, with a simple non helpful message , "There were deployment errors".

### Detailed repro steps so we can see the same problem

1. Create class library
2. create standard application
3. Add reference to class library
4. Build and deploy and check ok
5. unload class library project
6.  Attempt to debug
...

### Expected behaviour

Check and report on the referenced project is unloaded and must be reloaded to successfully deploy application

### Additional context

Not an important issue

### Make an effort to fix the bug

Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by josesimoes** [comment]
This behavior it's coming from Visual Studio. Our project system can't override or circumvent that...
