### ISSUE TITLE
RemovableDeviceInserted does not fire if nanoFramework.System.IO.FileSystem Installed

### ISSUE THREAD

**Issue by gligorov** [nanoframework/Home#874]
### Details about Problem
Seems that the event is no longer firing after the latest updates and if nanoFramework.System.IO.FileSystem is installed.   Using USB inserted into ORGPAL_PALTHREE latest image, and nothing happens on USB Insert of flash drive.  

**nanoFramework area:**  Storage area. 

**Target:** ORGPAL_PALTHREE

### Description

The StorageEventManager_RemovableDeviceInserted event no longer fires when a USB Flash drive is inserted. Was working fine with image from a week ago.

### Detailed repro steps so we can see the same problem

1.  Run the RemovableDeviceEvent Sample
2. Install the nanoFramework.System.IO.FileSystem ( not needed but causes the issue)
3. Insert a USB Flash drive in device, no event is fired
4. Remove the nanoFramework.System.IO.FileSystem package and repeat process it all works.

#### Sample Project

Just use the Storage Sample ->  RemovableDeviceEvent

**Comment by josesimoes** [comment]
@gligorov I believe this is fixed now. Can you please confirm and close it that's the case?

**Comment by gligorov** [comment]
Yes, all seems good with the latest build.
