### ISSUE TITLE
Review S.IO.FileSystem namespaces

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#875]
### Details about Problem

**nanoFramework area:** (C# code )

### Description
- nanespaces in S.IO.FileSystem are overlapping some from mscorlib which is causing issues for example when using resources, because of the class names on the attributes there.

### Detailed repro steps so we can see the same problem

1. Add ref to ResourcesManager and S.IO.FileSystem

2. Add resource (any)
3. Build will fail on "missing" classes in the attributes.

**Comment by AdrianSoundy** [comment]
@josesimoes 
Tried to reproduce this but unable.
1) - New project
2) - Add resource manager, add string resource
3)- Build OK
4)- Add System.IO.Filesystem, build still OK
5) - Add Get string resource and Open FileStream
6) - Build OK

**Comment by josesimoes** [comment]
Just tried it again and it seems to be working. Could have been some temporary issue on the test project I was using. Closing this.
