### ISSUE TITLE
Port Listening Not Work ON WIFIAP Mode! ESP32

### ISSUE THREAD

**Issue by AlirezaP** [nanoframework/Home#882]
### Details about Problem

**.nanoFramework.WebServer
**.Windows.Devices.WiFi

**ESP32 WROOM**

### Description
i configure networkInterfaceType to WirelessAP, and i can see the device in my wifi list also i can connect to device wifi with my pc but i cant to connect device with specific port that i listening on it before:

'

        public static bool ConfiWIFIAPMode()
        {
            string SoftApIP = "192.168.1.67";

            var myNI = NetworkInterface.GetAllNetworkInterfaces();

            NetworkInterface current = null;
            WirelessAPConfiguration wapconf = null;
            foreach (NetworkInterface ni in myNI)
            {
                if (ni.NetworkInterfaceType == NetworkInterfaceType.WirelessAP)
                {
                    current = ni;
                    wapconf = WirelessAPConfiguration.GetAllWirelessAPConfigurations()[ni.SpecificConfigId];
                    break;
                }
            }

            // Check if already Enabled and return true
            if (wapconf.Options == (WirelessAPConfiguration.ConfigurationOptions.Enable |
                                    WirelessAPConfiguration.ConfigurationOptions.AutoStart) &&
                current.IPv4Address == SoftApIP)
            {
                return true;
            }

            // Set up IP address for Soft AP
            current.EnableStaticIPv4(SoftApIP, "255.255.255.0", SoftApIP);

            wapconf.Options = WirelessAPConfiguration.ConfigurationOptions.AutoStart |
                            WirelessAPConfiguration.ConfigurationOptions.Enable;

            wapconf.Ssid = "nano_Alireza_2";

            wapconf.MaxConnections = 5;

            wapconf.Authentication = System.Net.NetworkInformation.AuthenticationType.Open;
            wapconf.Password = "";

            wapconf.SaveConfiguration();

            return false;
        }

        static Thread _serverThread = null;
        public static void StartWebServerThread()
        {
            _serverThread = new Thread(StartWebServer);
            _serverThread.Start();
        }

        public static void StartWebServer()
        {

            using (WebServer server = new WebServer(80, HttpProtocol.Http))
            {
               // Add a handler for commands that are received by the server.
                server.CommandReceived += Server_CommandReceived;
                // Start the server.
                server.Start();

                Thread.Sleep(Timeout.Infinite);
            }
        }

        public static void Main()
        {
            if (ConfiWIFIAPMode() == false)
            {
                // Reboot device to Activate Access Point on restart
                Debug.WriteLine($"Setup Soft AP, Rebooting device");
                Power.RebootDevice();
            }

            StartWebServerThread();
            Thread.Sleep(Timeout.Infinite);
        }

' 

1.run the project
2.connect to the devices wifi,
3.try telnet 192.168.1.67 80 (it faile!)
  "Connecting To 192.168.1.67...Could not open connection to the host, on port 80: Connect failed"

 I was traced code (nanoFramework.WebServer , Windows.Devices.WiFi) but I didn't found Bug

I would be happy if I could help 

### Additional context
may be the problem is about ip binding ....

**Comment by JeremyKnaggs** [comment]
curious if these two issues are related: #885
