### ISSUE TITLE
ESP32 SDCard reinitialize issue

### ISSUE THREAD

**Issue by alberk8** [nanoframework/Home#894]
### Details about Problem
When SDCard is disposed subsequent reinitialization will fail.

**Target:**
ESP32 WROVER

**Firmware image version:**
1.7.1-preview.1125

Worked before? If so, with which nanoFramework image version:
Not sure.

### Description

An exception is thrown when subsequent attempt to reinitialized the SDCard class.

### Detailed repro steps so we can see the same problem
```
 var mycard = new SDCard(new SDCard.SDCardMmcParameters { dataWidth = SDCard.SDDataWidth._4_bit });
 mycard.Mount();
 mycard.Unmount();
 mycard.Dispose();

// fail here
var mycard1 = new SDCard(new SDCard.SDCardMmcParameters { dataWidth = SDCard.SDDataWidth._4_bit });
 mycard1.Mount();
 mycard1.Unmount();
 mycard1.Dispose();

```

### Other suggested things
Exception Thrown
```
++++ Exception System.Exception - CLR_E_PIN_UNAVAILABLE (1) ++++
++++ Message: 
++++ nanoFramework.System.IO.FileSystem.SDCard::InitNative [IP: 0000] ++++
++++ nanoFramework.System.IO.FileSystem.SDCard::.ctor [IP: 0025] ++++
++++ nanoFrameworkSDCard.Program::Main [IP: 0029] ++++
Exception thrown: 'System.Exception' in System.IO.FileSystem.dll
An unhandled exception of type 'System.Exception' occurred in System.IO.FileSystem.dll

```
### Expected behaviour
SDCard class should not throw exception if it was previously disposed.

**Comment by AdrianSoundy** [comment]
Looks like a problem removing reserve from SDIO pins.
