### ISSUE TITLE
Tiny fixes required in some samples

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#902]
### Details about Problem

**nanoFramework area:** (Samples)

### Description

Some samples need tiny adjustments because some APIs have changed. 
Please check nanoframework/Samples#183

1. Clone locally
2. Check sample whose build is failing in the PR checks
3. Fix code
4. Push commit

**Comment by networkfusion** [comment]
@Ellerbach any chance you can provide input / fix the cause of 
![image](https://user-images.githubusercontent.com/11439699/145177970-f513bdb3-3221-4934-94cc-3f4fdcfc695d.png)

I cannot see any evidence of that function ever existing.

**Comment by josesimoes** [comment]
Fixed in nanoframework/Samples#191.
