### ISSUE TITLE
Method Equals doesn't work correctly for ValueTypes

### ISSUE THREAD

**Issue by alexxxz1977** [nanoframework/Home#910]
### Details about Problem

**.NET nanoFramework library:** nanoFramework.CoreLibrary 1.11.7

**VS version:** 2019

**VS extension version:** 2019.10.0.2

**Target:** esp32

**Device capabilities output:**

### Description

When you try to compare two enum values using method Equals it shows that they are not identical, regardless that both items have the same HashCode. See the example below.

### Detailed repro steps so we can see the same problem

1. Parse and run the code below
2. In all cases it should True in the console

### Expected behaviour

All cases should produce the same output

#### Sample Project

public enum AAA { A = 1, B = 2, C = 3 }

public static void Main()
{
  var f = AAA.A;
  var f1 = AAA.A;

  Debug.WriteLine(f.Equals(f1) ? "True": "False");
  Debug.WriteLine(f == f1 ? "True" : "False");
  Debug.WriteLine(f.GetHashCode() == f1.GetHashCode() ? "True" : "False");

  Thread.Sleep(Timeout.Infinite);
}

**Comment by alexxxz1977** [comment]
I found that issue is related to this commit - https://github.com/nanoframework/nf-interpreter/commit/4736fdcf102388a6741dc11a7fc2af1ae73f3f50. When you revert it back, everything is working fine.

**Comment by josesimoes** [comment]
> I found that issue is related to this commit - [nanoframework/nf-interpreter@4736fdc](https://github.com/nanoframework/nf-interpreter/commit/4736fdcf102388a6741dc11a7fc2af1ae73f3f50). When you revert it back, everything is working fine.

Thanks for finding this, it will be helpful when working on it. Because that other commit was a fix to some other issue, it can't simply be reverted. Another fix that addresses both issues has to be implemented.
