### ISSUE TITLE
ESP32_BLE_REV3 nightly build failing

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#923]
### Details about Problem
![image](https://user-images.githubusercontent.com/11439699/147833890-81e607ff-4e7b-4497-8dcc-4fb19f41f878.png)

**Target:**
ESP32_BLE_REV3 nightly builds

**Firmware image version:**
Latest.

Worked before? If so, with which nanoFramework image version:

**Device capabilities output:**

### Description

Relivent bit is:

```
extern_ram_seg:          0 GB         4 MB      0.00c:/users/vssadministrator/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: nanoCLR.elf section `.iram0.text' will not fit in region `iram0_0_seg'
c:/users/vssadministrator/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: IRAM0 segment data does not fit.
c:/users/vssadministrator/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `iram0_0_seg' overflowed by 1156 bytes
collect2.exe: error: ld returned 1 exit status

```

### Detailed repro steps so we can see the same problem

1.

2.

...

### Make an effort to fix the bug

Attempt to submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by networkfusion** [comment]
Perhaps related with https://github.com/nanoframework/Home/issues/919

**Comment by josesimoes** [comment]
Reported on Discord Core Team channel after the move to IDF 4.3.2. Request @AdrianSoundy to look at this.
