### ISSUE TITLE
System.NET TCPListner Socket.Accept() fails after 3 connections

### ISSUE THREAD

**Issue by Feiko** [nanoframework/Home#926]
### Details about Problem

**.NET nanoFramework library:** System.NET

**VS version:** 2022

**VS extension version:** not relevant

**Target:**ESP32 (multiple versions)

**Device capabilities output:**

### Description
When using a listening TCP Socket only 3 clients can connect. On the 4th connection socket.Accept() throws: ++++ Exception System.Net.Sockets.SocketException - CLR_E_FAIL (1) ++++

### Detailed repro steps so we can see the same problem

1.
`var listenPoint = new IPEndPoint(IPAddress.Any, 80);
            Socket mySocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);

            mySocket.Bind(listenPoint);
            mySocket.Listen(4);
            Console.WriteLine("Socket listening!");

            while (true)
            {

                var socket = mySocket.Accept();
                NetworkStream networkStream = new NetworkStream(socket);
                Debug.WriteLine("new networkstream");
            }
            mySocket.Close();`

2. Use Curl or a browser to open 4 connections.

3. Output shows:

```
Socket listening!
new networkstream
new networkstream
new networkstream
    ++++ Exception System.Net.Sockets.SocketException - CLR_E_FAIL (1) ++++
    ++++ Message: 
    ++++ System.Net.Sockets.NativeSocket::accept [IP: 0000] ++++
    ++++ System.Net.Sockets.Socket::Accept [IP: 001c] ++++
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.dll
An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.Net.dll
```

### Expected behaviour
Should be able to connect more TCP socket clients. 

#### Sample Project

See repro steps

### Screenshot
none

### Additional context
Is an issue when using i.e. the Websocket.Server lib. Also overall TCP sockets appear to be unstable i.e. 2 client requests simultaneously or difficulty getting socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Linger, true)  to work. 

### I've made an effort to fix the bug
I tried to debug further but I was unable to build the System.NET locally. I could not find any problem in the System.NET code.

**Comment by josesimoes** [comment]
Fixed with nanoframework/nf-interpreter#2209.
