### ISSUE TITLE
Implementation of Environment.TickCount64

### ISSUE THREAD

**Issue by oblaise** [nanoframework/Home#943]
**nanoFramework area:** Core Library

### Is your feature request related to a problem? Please describe.
There is often needs to measure the time between two locations in code. I.e. a loop duration, the time between 2 udp packets received, timeout for connecting external devices...

### Describe the solution you'd like
An implementation of `Environment.TickCount64` [and/or `Environment.TickCount`] that relies closely on the native clock with as less overhead as possible. This should return a value in millisecond to map to the .NET implementation. The value itself isn't really significant when you have to deal with time difference but knowing the origin of the value is a plus if possible.

### Describe alternatives you've considered
Using the value retrieved from `DateTime.UtcNow.TickCount`. This work but requires creation of a new DateTime struct each time it is called generating important overhead that makes the measure less reliable.

### Additional context
If accepted and while adding the Environment class some other fields could be useful also (i.e. OSVersion / Version / NewLine) and simplify work of people porting existing libraries to nF. 

### Submit a PR with the implementation
N/A

**Comment by josesimoes** [comment]
@oblaise in case you've missed it, most of those properties (and more) are already available here:
https://docs.nanoframework.net/api/nanoFramework.Runtime.Native.SystemInfo.html
