### ISSUE TITLE
Migrate Keypad PCF8574 from nf-Community-Contribution to Iot.Device

### ISSUE THREAD

**Issue by Ellerbach** [nanoframework/Home#974]
Need some adjustments to fit the IoT.Device requirements.
Most likely needs to adjustments as well to fit with the existing keypad in IoT.Devices.
Binding to migrate: https://github.com/nanoframework/nf-Community-Contributions/tree/master/drivers/Keypad-PCF8574

**Comment by josesimoes** [comment]
Completed with nanoframework/nanoFramework.IoT.Device#303.
