### ISSUE TITLE
Add Security to Bluetooth

### ISSUE THREAD

**Issue by wjax** [nanoframework/Home#977]
### Description

Bluetooth functionality does not support security, no authentication and no encryption is implemented.

### How to solve the problem

Add security to bluetooth

### Aditional context

Trying to modify NordicSPP to add the following but does nothing

```csharp
// Define TX characteristic
GattLocalCharacteristicParameters txParam = new GattLocalCharacteristicParameters()
{
    UserDescription = "TX Characteristic",
    WriteProtectionLevel = GattProtectionLevel.EncryptionAndAuthenticationRequired,
    ReadProtectionLevel= GattProtectionLevel.EncryptionAndAuthenticationRequired,
    CharacteristicProperties = GattCharacteristicProperties.Notify,
};
```

```csharp
// Define RX characteristic
GattLocalCharacteristicParameters rxParam = new GattLocalCharacteristicParameters()
{
    UserDescription = "RX Characteristic",
    ReadProtectionLevel = GattProtectionLevel.EncryptionAndAuthenticationRequired,
    WriteProtectionLevel = GattProtectionLevel.EncryptionAndAuthenticationRequired, 
    CharacteristicProperties = GattCharacteristicProperties.Write | GattCharacteristicProperties.WriteWithoutResponse
};
```

**Comment by AdrianSoundy** [comment]
Added the extra Authentication & Encryption flags to Characteristic and Descriptor definitions.

When Authentication enabled forces pairing for becomes bonded

**Comment by AdrianSoundy** [comment]
@wjax 
Please test this change and if any problem reopen issue

**Comment by AdrianSoundy** [comment]
Just flash the latest preview nanoFramework firmware.  No change to managed code.

**Comment by AdrianSoundy** [comment]
Unless you are compiling you own nanoClr version, then pull latest from github and compile
@wjax

**Comment by AdrianSoundy** [comment]
For some reason I don't see this post in the github issue just repling from
received email. I can look if its possible to do something outside nimble
to force encryption on notify. Best to raise a separate issue for this.
