### ISSUE TITLE
Add Central/Client capability to Bluetooth

### ISSUE THREAD

**Issue by alberk8** [nanoframework/Home#981]
### Description

The current Bluetooth Library does not support connecting to peripheral Bluetooth device/sensor.

### How to solve the problem

Implement Client/Central role capability in Bluetooth Library

**Comment by AdrianSoundy** [comment]
This is in progress.
Currently working on the BluetoothLEAdvertisementWatcher class

**Comment by alberk8** [comment]
> This is in progress. Currently working on the BluetoothLEAdvertisementWatcher class
> 
> Still have to decide how to control which role the code is running Peripheral or Central. Maybe if you start the Peripheral/service advertising then in Peripheral /server role and Central tasks will give error.

I guess for a start, when one mode is running the other should be prevented to run.  I know that both can run simultaneously but on ESP32 it will be a stretch to get it running stable.
