### ISSUE TITLE
Implicit ToString() is not working on some types

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#989]
### Details about Problem

**nanoFramework area:** (mscolib)

### Description
- When working in nanoframework/CoreLibrary#177 noticed that when running the Reflection sample, those implicit calls to ToString are not working for some types. Outputting the content of the DataRowAttribute fails for strings and bools. (~line 64 of Reflection\CustomAttributes\Program.cs).

**Comment by jonstelly** [comment]
For Enums their `ToString()` returns their integer as a string.
`Console.WriteLine($"{DayOfWeek.Monday} - {DayOfWeek.Monday.ToString()}");`
outputs
`1 - 1`

**Comment by josesimoes** [comment]
> For Enums their `ToString()` returns their integer as a string.
> `Console.WriteLine($"{DayOfWeek.Monday} - {DayOfWeek.Monday.ToString()}");`
> outputs
> `1 - 1`

https://docs.nanoframework.net/content/architecture/simplifications-and-trade-offs.html#enums
